import React, { useState, useEffect, useCallback } from 'react';
import {
  ChevronDown,
  ChevronRight,
  Copy,
  CheckCircle,
  AlertCircle,
  Loader2,
  Terminal,
  Heart,
  Wrench,
  FileCode2,
  Globe,
  Plus,
  X,
} from 'lucide-react';
import {
  loadAllComponents,
  loadRemoteComponent,
  checkComponentHealth,
  queryDialectUrls,
  getStoredDialectUrls,
  addStoredDialectUrl,
  removeStoredDialectUrl,
  ComponentInfo,
  ComponentManifest,
} from '../parser/languageCatalog';
import { useAppContext } from '../context/AppContext';

/** Actor declared in the test case Background (from IR declareActor actions) */
export interface RequiredActor {
  id: string;
  endpoint?: string;
}

interface ComponentsPanelProps {
  isDark: boolean;
  requiredActors?: RequiredActor[];
  onComponentsChange?: (components: ComponentInfo[]) => void;
}

// ── Helpers ──────────────────────────────────────────────────────────

/** Derive the default endpoint from the manifest port mapping */
function defaultEndpoint(manifest: ComponentManifest): string {
  const port = manifest.docker?.ports?.[0]?.split(':')[0] || '8080';
  return `http://localhost:${port}`;
}

/** Load saved endpoint from localStorage or derive from manifest.
 *  Clears stale cached values that were saved with a wrong port. */
function getEndpoint(manifest: ComponentManifest): string {
  const def = defaultEndpoint(manifest);
  const stored = localStorage.getItem(`component:${manifest.id}:endpoint`);
  if (stored && stored !== def) {
    // Keep user-customized endpoints, but clear auto-derived ones with wrong port
    const looksAutoGenerated = /^https?:\/\/localhost:\d+$/.test(stored);
    if (looksAutoGenerated) {
      localStorage.removeItem(`component:${manifest.id}:endpoint`);
      return def;
    }
    return stored;
  }
  return def;
}

function saveEndpoint(id: string, url: string) {
  localStorage.setItem(`component:${id}:endpoint`, url);
}

/** Generate a docker run command for a component */
function dockerRunCmd(m: ComponentManifest): string {
  const parts = ['docker run -d'];
  parts.push(`--name ${m.id}`);
  for (const p of m.docker?.ports ?? []) parts.push(`-p ${p}`);
  for (const e of m.docker?.environment ?? []) parts.push(`-e "${e}"`);
  parts.push(m.docker?.image ?? 'unknown');
  return parts.join(' \\\n  ');
}

/** Generate docker-compose services block for enabled components */
function dockerComposeYaml(components: ComponentInfo[]): string {
  const enabled = components.filter(c => c.enabled && c.manifest.docker);
  if (enabled.length === 0) return '# No components enabled';

  const lines = ['version: "3.8"', 'services:'];
  for (const c of enabled) {
    const m = c.manifest;
    lines.push(`  ${m.id}:`);
    lines.push(`    image: ${m.docker!.image}`);
    if (m.docker!.ports?.length) {
      lines.push('    ports:');
      for (const p of m.docker!.ports!) lines.push(`      - "${p}"`);
    }
    if (m.docker!.environment?.length) {
      lines.push('    environment:');
      for (const e of m.docker!.environment!) lines.push(`      - ${e}`);
    }
    if (m.healthCheck) {
      lines.push('    healthcheck:');
      lines.push(`      test: ["CMD", "curl", "-f", "http://localhost:${m.docker!.ports?.[0]?.split(':')[1] || '8080'}${m.healthCheck.path}"]`);
      lines.push('      interval: 30s');
      lines.push('      timeout: 5s');
      lines.push('      retries: 3');
    }
    lines.push('');
  }
  return lines.join('\n');
}

// ── Main Panel ───────────────────────────────────────────────────────

export function ComponentsPanel({ isDark, requiredActors, onComponentsChange }: ComponentsPanelProps) {
  const { dialectsVersion, refreshDialects } = useAppContext();
  const [components, setComponents] = useState<ComponentInfo[]>([]);
  const [loading, setLoading] = useState(true);
  const [showCompose, setShowCompose] = useState(false);
  const [copied, setCopied] = useState<string | null>(null);

  useEffect(() => {
    (async () => {
      setLoading(true);
      const comps = await loadAllComponents();
      setComponents(comps);
      setLoading(false);
      // Auto-check health of all enabled components
      for (const comp of comps) {
        if (comp.enabled && comp.manifest.healthCheck) {
          const endpoint = getEndpoint(comp.manifest);
          checkComponentHealth(comp.manifest, endpoint).then(status => {
            setComponents(prev =>
              prev.map(c => c.manifest.id === comp.manifest.id ? { ...c, status } : c)
            );
          });
        }
      }
    })();
  }, [dialectsVersion]);

  const updateComponent = useCallback((id: string, patch: Partial<ComponentInfo>) => {
    setComponents(prev => {
      const next = prev.map(c => c.manifest.id === id ? { ...c, ...patch } : c);
      return next;
    });
  }, []);

  const toggleComponent = (id: string) => {
    setComponents(prev => {
      const next = prev.map(c =>
        c.manifest.id === id ? { ...c, enabled: !c.enabled } : c
      );
      const comp = next.find(c => c.manifest.id === id);
      if (comp) {
        localStorage.setItem(`component:${id}:enabled`, String(comp.enabled));
      }
      onComponentsChange?.(next);
      return next;
    });
  };

  const checkHealth = async (comp: ComponentInfo, endpoint?: string) => {
    updateComponent(comp.manifest.id, { status: 'checking' });
    const status = await checkComponentHealth(comp.manifest, endpoint);
    updateComponent(comp.manifest.id, { status });
  };

  const checkAll = async () => {
    for (const comp of components) {
      const endpoint = getEndpoint(comp.manifest);
      await checkHealth(comp, endpoint);
    }
  };

  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    setCopied(label);
    setTimeout(() => setCopied(null), 2000);
  };

  if (loading) {
    return (
      <div className="p-4 flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
        <Loader2 size={14} className="animate-spin" /> Loading components...
      </div>
    );
  }

  const enabledCount = components.filter(c => c.enabled).length;
  const healthyCount = components.filter(c => c.status === 'healthy').length;

  return (
    <div className="h-full overflow-auto">
      {/* ── Header ────────────────────────────────────────────── */}
      <div className="sticky top-0 z-10 bg-white dark:bg-slate-900 border-b border-gray-200 dark:border-slate-700 px-4 py-3">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-200">
              Test Image Components
            </h3>
            <p className="text-[10px] text-gray-400 dark:text-gray-500 mt-0.5">
              {enabledCount} enabled
              {healthyCount > 0 && <span className="text-green-500"> / {healthyCount} healthy</span>}
            </p>
          </div>
          <div className="flex gap-1.5">
            <button
              onClick={() => setShowCompose(!showCompose)}
              className={`px-2 py-1 text-[10px] font-medium rounded flex items-center gap-1 transition-colors ${
                showCompose
                  ? 'bg-blue-500 text-white'
                  : 'bg-gray-100 dark:bg-slate-700 text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-slate-600'
              }`}
            >
              <Terminal size={10} /> Compose
            </button>
            <button
              onClick={checkAll}
              className="px-2 py-1 text-[10px] font-medium rounded bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-300 hover:bg-green-200 dark:hover:bg-green-900/50 transition-colors flex items-center gap-1"
            >
              <Heart size={10} /> Check All
            </button>
          </div>
        </div>
      </div>

      {/* ── Docker Compose panel ──────────────────────────────── */}
      {showCompose && (
        <div className="mx-4 mt-3 rounded-lg border border-blue-200 dark:border-blue-800 bg-blue-50/50 dark:bg-blue-950/20 overflow-hidden">
          <div className="flex items-center justify-between px-3 py-2 border-b border-blue-200 dark:border-blue-800">
            <span className="text-[11px] font-medium text-blue-700 dark:text-blue-300">
              docker-compose.yml
            </span>
            <button
              onClick={() => copyToClipboard(dockerComposeYaml(components), 'compose')}
              className="text-[10px] text-blue-600 dark:text-blue-400 hover:underline flex items-center gap-1"
            >
              {copied === 'compose' ? <><CheckCircle size={10} /> Copied</> : <><Copy size={10} /> Copy</>}
            </button>
          </div>
          <pre className="px-3 py-2 text-[11px] font-mono text-gray-700 dark:text-gray-300 overflow-x-auto max-h-48 whitespace-pre">
            {dockerComposeYaml(components)}
          </pre>
        </div>
      )}

      {/* ── Required by test case ─────────────────────────────── */}
      {requiredActors && requiredActors.length > 0 && (
        <div className="mx-4 mt-3 rounded-lg border border-amber-200 dark:border-amber-800 bg-amber-50/50 dark:bg-amber-950/20 overflow-hidden">
          <div className="px-3 py-2 border-b border-amber-200 dark:border-amber-800">
            <span className="text-[11px] font-medium text-amber-700 dark:text-amber-300">
              Required by test case
            </span>
          </div>
          <div className="px-3 py-2 space-y-1.5">
            {requiredActors.map(actor => {
              // Find which component provides this actor
              const provider = components.find(c =>
                c.manifest.actors?.some(a => a.id === actor.id)
              );
              const isEnabled = provider?.enabled ?? false;
              const status = provider?.status ?? 'unknown';

              const statusLabel = status === 'healthy' ? 'healthy'
                : status === 'unhealthy' ? 'unreachable'
                : status === 'checking' ? 'checking...'
                : isEnabled ? 'not checked'
                : 'disabled';

              const dotColor = status === 'healthy' ? 'bg-green-400'
                : status === 'unhealthy' ? 'bg-red-400'
                : status === 'checking' ? 'bg-yellow-400 animate-pulse'
                : isEnabled ? 'bg-yellow-400'
                : provider ? 'bg-gray-400'
                : 'bg-red-400';

              const badgeColor = status === 'healthy'
                ? 'bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-300'
                : status === 'unhealthy'
                ? 'bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-300'
                : isEnabled
                ? 'bg-yellow-100 dark:bg-yellow-900/30 text-yellow-700 dark:text-yellow-300'
                : 'bg-gray-100 dark:bg-slate-700 text-gray-500 dark:text-gray-400';

              return (
                <div key={actor.id} className="flex items-center gap-2 text-[11px]">
                  {/* Status indicator */}
                  <span className={`w-2 h-2 rounded-full flex-shrink-0 ${dotColor}`} />
                  {/* Actor name */}
                  <span className="font-mono font-medium text-gray-700 dark:text-gray-200">
                    {actor.id}
                  </span>
                  {/* Provider info */}
                  {provider ? (
                    <span className={`text-[10px] px-1.5 py-0.5 rounded ${badgeColor}`}>
                      {provider.manifest.name} — {statusLabel}
                    </span>
                  ) : (
                    <span className="text-[10px] px-1.5 py-0.5 rounded bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-300">
                      no component available
                    </span>
                  )}
                  {/* Endpoint from feature file */}
                  {actor.endpoint && (
                    <span className="text-[10px] text-gray-400 dark:text-gray-500 font-mono ml-auto truncate max-w-[180px]" title={actor.endpoint}>
                      {actor.endpoint}
                    </span>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* ── Plugin dialects (remote, by URL) ─────────────────── */}
      <DialectSourcesSection onChanged={refreshDialects} />

      {/* ── Component cards ───────────────────────────────────── */}
      <div className="px-4 py-3 space-y-3">
        {components.length === 0 ? (
          <p className="text-xs text-gray-400 dark:text-gray-500">
            No components found. Add component manifests to <code>public/components/</code>.
          </p>
        ) : (
          components.map(comp => {
            const isRequired = requiredActors?.some(a =>
              comp.manifest.actors?.some(ca => ca.id === a.id)
            ) ?? false;
            return (
              <ComponentCard
                key={comp.manifest.id}
                component={comp}
                isRequired={isRequired}
                onToggle={() => toggleComponent(comp.manifest.id)}
                onCheckHealth={(endpoint) => checkHealth(comp, endpoint)}
                onCopy={(text, label) => copyToClipboard(text, label)}
                copied={copied}
              />
            );
          })
        )}
      </div>
    </div>
  );
}

// ── Plugin dialect sources ───────────────────────────────────────────

/** Manage remote plugin dialects: base URLs of a plugin repo's dialect/
 *  folder (component.yml + steps.yml [+ scriptlets/]). The bundled
 *  fhir-validator dialect stays the default; remote dialects with the same
 *  id override it, others are added alongside. Persisted in localStorage. */
function DialectSourcesSection({ onChanged }: { onChanged: () => void }) {
  const [stored, setStored] = useState<string[]>(() => getStoredDialectUrls());
  const [input, setInput] = useState('');
  const [adding, setAdding] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const fromQuery = queryDialectUrls();

  const add = async () => {
    const url = input.trim().replace(/\/+$/, '');
    if (!url) return;
    setAdding(true);
    setError(null);
    const remote = await loadRemoteComponent(url);
    if (!remote) {
      setError('No loadable dialect at this URL — it must serve component.yml (+ steps.yml) with CORS enabled.');
      setAdding(false);
      return;
    }
    setStored(addStoredDialectUrl(url));
    setInput('');
    setAdding(false);
    onChanged();
  };

  const remove = (url: string) => {
    setStored(removeStoredDialectUrl(url));
    onChanged();
  };

  return (
    <div className="mx-4 mt-3 rounded-lg border border-gray-200 dark:border-slate-700 bg-white dark:bg-slate-800/60 overflow-hidden">
      <div className="flex items-center gap-1.5 px-3 py-2 border-b border-gray-100 dark:border-slate-700">
        <Globe size={11} className="text-blue-500 dark:text-blue-400" />
        <span className="text-[11px] font-medium text-gray-700 dark:text-gray-300">Plugin dialects</span>
        <span className="text-[9px] text-gray-400 dark:text-gray-500 ml-auto">
          fhir-validator bundled by default
        </span>
      </div>
      <div className="px-3 py-2 space-y-1.5">
        {fromQuery.map(url => (
          <div key={`q-${url}`} className="flex items-center gap-2 text-[10px]">
            <span className="flex-1 font-mono text-gray-600 dark:text-gray-300 truncate" title={url}>{url}</span>
            <span className="px-1.5 py-0.5 rounded bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300">?dialects=</span>
          </div>
        ))}
        {stored.map(url => (
          <div key={url} className="flex items-center gap-2 text-[10px] group">
            <span className="flex-1 font-mono text-gray-600 dark:text-gray-300 truncate" title={url}>{url}</span>
            <button
              onClick={() => remove(url)}
              className="p-0.5 rounded text-gray-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 transition-colors"
              title="Remove dialect"
            >
              <X size={11} />
            </button>
          </div>
        ))}
        <div className="flex gap-1.5 pt-0.5">
          <input
            type="text"
            value={input}
            onChange={e => { setInput(e.target.value); setError(null); }}
            onKeyDown={e => { if (e.key === 'Enter') add(); }}
            placeholder="https://…/itb-plugin-x/main/dialect"
            className="flex-1 px-2 py-1 text-[10px] font-mono border border-gray-300 dark:border-slate-600 rounded bg-white dark:bg-slate-900 text-gray-800 dark:text-gray-200 focus:ring-1 focus:ring-blue-500 focus:border-transparent"
          />
          <button
            onClick={add}
            disabled={adding || !input.trim()}
            className="px-2 py-1 text-[10px] font-medium rounded bg-blue-500 text-white hover:bg-blue-600 disabled:opacity-40 transition-colors flex items-center gap-1"
          >
            {adding ? <Loader2 size={10} className="animate-spin" /> : <Plus size={10} />}
            Add
          </button>
        </div>
        {error && (
          <p className="text-[10px] text-red-600 dark:text-red-400">{error}</p>
        )}
      </div>
    </div>
  );
}

// ── Component Card ───────────────────────────────────────────────────

function ComponentCard({
  component: comp,
  isRequired,
  onToggle,
  onCheckHealth,
  onCopy,
  copied,
}: {
  component: ComponentInfo;
  isRequired: boolean;
  onToggle: () => void;
  onCheckHealth: (endpoint?: string) => void;
  onCopy: (text: string, label: string) => void;
  copied: string | null;
}) {
  const [expanded, setExpanded] = useState(false);
  const [endpoint, setEndpoint] = useState(() => getEndpoint(comp.manifest));
  const [activeTab, setActiveTab] = useState<'setup' | 'steps'>('setup');

  const m = comp.manifest;

  const statusConfig: Record<string, { color: string; label: string; icon?: React.ReactNode }> = {
    unknown: { color: 'bg-gray-300 dark:bg-gray-600', label: 'Not checked' },
    healthy: { color: 'bg-green-400', label: 'Healthy', icon: <CheckCircle size={10} className="text-green-500" /> },
    unhealthy: { color: 'bg-red-400', label: 'Unreachable', icon: <AlertCircle size={10} className="text-red-500" /> },
    checking: { color: 'bg-yellow-400 animate-pulse', label: 'Checking...', icon: <Loader2 size={10} className="animate-spin text-yellow-500" /> },
  };

  const st = statusConfig[comp.status] || statusConfig.unknown;

  const handleEndpointChange = (val: string) => {
    setEndpoint(val);
    saveEndpoint(m.id, val);
  };

  const handlePing = () => {
    onCheckHealth(endpoint);
  };

  return (
    <div
      className={`rounded-lg border transition-all ${
        comp.enabled
          ? 'border-blue-200 dark:border-blue-800 bg-white dark:bg-slate-800/80'
          : 'border-gray-200 dark:border-slate-700 bg-gray-50 dark:bg-slate-800/40 opacity-70'
      }`}
    >
      {/* ── Header row ─────────────────────────── */}
      <div className="flex items-center gap-2 px-3 py-2.5 cursor-pointer" onClick={() => setExpanded(!expanded)}>
        <span className={`w-2 h-2 rounded-full flex-shrink-0 ${st.color}`} />
        <button className="text-gray-400 dark:text-gray-500 flex-shrink-0">
          {expanded ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
        </button>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2">
            <span className="text-sm font-medium text-gray-800 dark:text-gray-100 truncate">
              {m.name}
            </span>
            <span className="text-[10px] text-gray-400 dark:text-gray-500">v{m.version}</span>
            {isRequired && (
              <span className="text-[9px] px-1.5 py-0.5 rounded-full bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-300 font-medium">
                required
              </span>
            )}
          </div>
        </div>
        <div className="flex items-center gap-1.5 flex-shrink-0" onClick={e => e.stopPropagation()}>
          {st.icon}
          <label className="relative inline-flex items-center cursor-pointer">
            <input type="checkbox" checked={comp.enabled} onChange={onToggle} className="sr-only peer" />
            <div className="w-8 h-4 bg-gray-300 dark:bg-slate-600 peer-checked:bg-blue-500 rounded-full transition-colors after:content-[''] after:absolute after:top-0.5 after:left-[2px] peer-checked:after:translate-x-4 after:bg-white after:rounded-full after:h-3 after:w-3 after:transition-all" />
          </label>
        </div>
      </div>

      {/* ── Tags row ───────────────────────────── */}
      <div className="px-3 pb-2 flex flex-wrap gap-1">
        {m.docker?.image && (
          <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] bg-gray-100 dark:bg-slate-700 text-gray-600 dark:text-gray-300 font-mono">
            {m.docker.image}
          </span>
        )}
        {m.actors?.map(a => (
          <span key={a.id} className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300">
            {a.id}
          </span>
        ))}
        {comp.extension && (
          <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-300">
            {comp.extension.steps.length} steps
          </span>
        )}
      </div>

      {/* ── Expanded body ──────────────────────── */}
      {expanded && (
        <div className="border-t border-gray-100 dark:border-slate-700">
          {/* Tabs */}
          <div className="flex border-b border-gray-100 dark:border-slate-700">
            <button
              onClick={() => setActiveTab('setup')}
              className={`flex-1 px-3 py-1.5 text-[11px] font-medium flex items-center justify-center gap-1 transition-colors ${
                activeTab === 'setup'
                  ? 'text-blue-600 dark:text-blue-400 border-b-2 border-blue-500 -mb-px'
                  : 'text-gray-400 dark:text-gray-500 hover:text-gray-600 dark:hover:text-gray-300'
              }`}
            >
              <Wrench size={11} /> Setup & Test
            </button>
            <button
              onClick={() => setActiveTab('steps')}
              className={`flex-1 px-3 py-1.5 text-[11px] font-medium flex items-center justify-center gap-1 transition-colors ${
                activeTab === 'steps'
                  ? 'text-blue-600 dark:text-blue-400 border-b-2 border-blue-500 -mb-px'
                  : 'text-gray-400 dark:text-gray-500 hover:text-gray-600 dark:hover:text-gray-300'
              }`}
            >
              <FileCode2 size={11} /> Language Steps
            </button>
          </div>

          {activeTab === 'setup' ? (
            <SetupTab
              manifest={m}
              endpoint={endpoint}
              status={comp.status}
              statusLabel={st.label}
              onEndpointChange={handleEndpointChange}
              onPing={handlePing}
              onCopy={onCopy}
              copied={copied}
            />
          ) : (
            <StepsTab extension={comp.extension} />
          )}
        </div>
      )}
    </div>
  );
}

// ── Setup Tab ────────────────────────────────────────────────────────

function SetupTab({
  manifest: m,
  endpoint,
  status,
  statusLabel,
  onEndpointChange,
  onPing,
  onCopy,
  copied,
}: {
  manifest: ComponentManifest;
  endpoint: string;
  status: string;
  statusLabel: string;
  onEndpointChange: (v: string) => void;
  onPing: () => void;
  onCopy: (text: string, label: string) => void;
  copied: string | null;
}) {
  const runCmd = dockerRunCmd(m);

  return (
    <div className="p-3 space-y-3">
      {/* Description */}
      {m.description && (
        <p className="text-[11px] text-gray-500 dark:text-gray-400">{m.description}</p>
      )}

      {/* Endpoint + health check */}
      <div>
        <label className="block text-[10px] font-medium text-gray-500 dark:text-gray-400 mb-1 uppercase tracking-wide">
          Endpoint URL
        </label>
        <div className="flex gap-1.5">
          <input
            type="text"
            value={endpoint}
            onChange={e => onEndpointChange(e.target.value)}
            className="flex-1 px-2.5 py-1.5 text-xs font-mono border border-gray-300 dark:border-slate-600 rounded-md bg-white dark:bg-slate-900 text-gray-800 dark:text-gray-200 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            placeholder="http://localhost:8080"
          />
          <button
            onClick={onPing}
            disabled={status === 'checking'}
            className={`px-3 py-1.5 text-[10px] font-medium rounded-md border transition-colors flex items-center gap-1 ${
              status === 'healthy'
                ? 'border-green-300 dark:border-green-700 bg-green-50 dark:bg-green-900/20 text-green-700 dark:text-green-300'
                : status === 'unhealthy'
                ? 'border-red-300 dark:border-red-700 bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-300'
                : 'border-gray-300 dark:border-slate-600 text-gray-600 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-slate-700'
            } disabled:opacity-40`}
          >
            {status === 'checking' ? (
              <><Loader2 size={10} className="animate-spin" /> Checking</>
            ) : status === 'healthy' ? (
              <><CheckCircle size={10} /> Healthy</>
            ) : status === 'unhealthy' ? (
              <><AlertCircle size={10} /> Failed</>
            ) : (
              <><Heart size={10} /> Ping</>
            )}
          </button>
        </div>
        {m.healthCheck && (
          <p className="mt-1 text-[10px] text-gray-400 dark:text-gray-500 font-mono">
            {m.healthCheck.method} {endpoint}{m.healthCheck.path}
            {m.healthCheck.expect?.status && ` → ${m.healthCheck.expect.status}`}
          </p>
        )}
      </div>

      {/* Docker run command */}
      {m.docker && (
        <div>
          <div className="flex items-center justify-between mb-1">
            <label className="text-[10px] font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wide">
              Docker Run
            </label>
            <button
              onClick={() => onCopy(runCmd, `docker-${m.id}`)}
              className="text-[10px] text-blue-600 dark:text-blue-400 hover:underline flex items-center gap-0.5"
            >
              {copied === `docker-${m.id}` ? <><CheckCircle size={9} /> Copied</> : <><Copy size={9} /> Copy</>}
            </button>
          </div>
          <pre className="px-2.5 py-2 text-[10px] font-mono bg-gray-900 dark:bg-black text-green-400 rounded-md overflow-x-auto whitespace-pre">
            {runCmd}
          </pre>
        </div>
      )}

      {/* Actors */}
      {m.actors && m.actors.length > 0 && (
        <div>
          <label className="block text-[10px] font-medium text-gray-500 dark:text-gray-400 mb-1 uppercase tracking-wide">
            Actors provided
          </label>
          <div className="space-y-1">
            {m.actors.map(a => (
              <div key={a.id} className="flex items-start gap-2 px-2.5 py-1.5 rounded bg-gray-50 dark:bg-slate-800">
                <span className="text-xs font-medium text-purple-700 dark:text-purple-300 font-mono">{a.id}</span>
                {a.description && (
                  <span className="text-[10px] text-gray-400 dark:text-gray-500">{a.description}</span>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ── Steps Tab ────────────────────────────────────────────────────────

function StepsTab({ extension }: { extension?: { steps: any[] } }) {
  if (!extension || extension.steps.length === 0) {
    return (
      <div className="p-3 text-xs text-gray-400 dark:text-gray-500">
        No language steps defined for this component.
      </div>
    );
  }

  return (
    <div className="p-3">
      <p className="text-[10px] text-gray-400 dark:text-gray-500 mb-2">
        {extension.steps.length} step patterns available when this component is enabled:
      </p>
      <div className="space-y-1 max-h-64 overflow-y-auto">
        {extension.steps.map((step: any, i: number) => {
          // Convert regex to a readable pattern
          const pattern = (step.match || '')
            .replace(/^\^/, '')
            .replace(/\$$/, '')
            .replace(/\([^)]*\)/g, (m: string) => {
              if (m.includes('A-Za-z')) return '<actor>';
              if (m.includes('http')) return '<url>';
              if (m.includes('[^"]+')) return '<value>';
              if (m.includes('[0-9]')) return '<number>';
              return '<...>';
            })
            .replace(/\\[.()[\]{}|?*+^$]/g, (m: string) => m.slice(1));

          const actionTypes = (step.actions || []).map((a: any) => {
            const key = Object.keys(a)[0];
            return key;
          });

          const uniqueActions = [...new Set<string>(actionTypes)];

          return (
            <div
              key={i}
              className="flex items-start gap-2 px-2 py-1.5 rounded hover:bg-gray-50 dark:hover:bg-slate-800 group"
            >
              <span className="text-[10px] text-gray-300 dark:text-gray-600 w-4 text-right flex-shrink-0 pt-0.5">
                {i + 1}
              </span>
              <div className="flex-1 min-w-0">
                <code className="text-[11px] text-gray-700 dark:text-gray-300 break-all">
                  {pattern}
                </code>
                <div className="flex gap-1 mt-0.5">
                  {uniqueActions.map((a: string) => (
                    <span key={a} className="text-[9px] px-1 py-0.5 rounded bg-gray-100 dark:bg-slate-700 text-gray-500 dark:text-gray-400">
                      {a}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
