# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at main).
# Suite "big": 5 tests for a FHIR 4.0 server. Do not edit; re-run the generator.
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the expected response is the upstream file,
# fetched at run time and compared as a matchetype by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:big @mode:general
Feature: Terminology server — big
  Testing handling a big code system

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r4"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/main/tests/"
    And TxServer is given the resources:
      | resource                       |
      | big/codesystem-big.json        |
      | big/codesystem-not-so-big.json |
      | big/valueset-big.json          |
      | big/valueset-big-circle1.json  |
      | big/valueset-big-circle2.json  |

  Rule: ValueSet $expand

    # This test is testing that a server can (a) defend itself against a request that is too big and
    # (b) returns the correct response when it does. The test is built in terms of 1000 codes, but the
    # actual limit doesn't matter as long as it's... big enough (loose definition). With regard to
    # Ontoserver, it has an internal limit far above 1000 codes. That's fine, but we really want to
    # know that if it's actual limit is exceeded, it'll return the correct response. So we add this
    # artificial header to tell Ontoserver to treat 1000 as an internal limit. This way we know that
    # if a real value set exceeds the internal cost limit, however that's determined, the response
    # will be correctly understood
    @operation:expand @http-code:4xx
    Scenario: big-echo-no-limit
      Given set header "X-TOO-COSTLY-THRESHOLD" to "1000"
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/big" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the expected response "big/expand-no-limit-outcome.json"

    @operation:expand
    Scenario: big-echo-zero-fifty-limit
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/big" },
            { "name": "count", "valueInteger": 50 },
            { "name": "offset", "valueInteger": 0 },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match one of the expected responses:
        | response                                          |
        | big/expand-zero-fifty-limit-valueset.json         |
        | big/expand-zero-fifty-limit-valueset-precise.json |

    @operation:expand
    Scenario: big-echo-fifty-fifty-limit
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/big" },
            { "name": "count", "valueInteger": 50 },
            { "name": "offset", "valueInteger": 50 },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match one of the expected responses:
        | response                                           |
        | big/expand-fifty-fifty-limit-valueset.json         |
        | big/expand-fifty-fifty-limit-valueset-precise.json |

    @operation:expand @http-code:4xx
    Scenario: big-circle-bang
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/big-circle-1" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the expected response "big/expand-circle-outcome.json"

  Rule: ValueSet $validate-code

    @operation:validate-code @http-code:4xx
    Scenario: big-circle-validate
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/big-circle-1" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/big",
                "code": "code470"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the expected response "big/validation-big-circle-response-outcome.json"
