# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at main).
# Suite "batch": 2 tests for a FHIR 4.0 server. Do not edit; re-run the generator.
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the expected response is the upstream file,
# fetched at run time and compared as a matchetype by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:batch @mode:general
Feature: Terminology server — batch
  Test Batch Validation

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r4"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/main/tests/"
    And TxServer is given the resources:
      | resource                      |
      | simple/codesystem-simple.json |

  Rule: ValueSet $batch-validate-code

    # Simple use of the batch validate operation
    @operation:batch-validate
    Scenario: batch-validate
      When Client validates a batch on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "tx-resource",
              "resource": {
                "resourceType": "ValueSet",
                "url": "urn:uuid:80458796-b204-4d17-ac1c-8443dd8cb35b",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "concept": [
                        {
                          "code": "code1"
                        },
                        {
                          "code": "code2"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "url", "valueUri": "urn:uuid:80458796-b204-4d17-ac1c-8443dd8cb35b" },
            {
              "name": "validation",
              "resource": {
                "resourceType": "Parameters",
                "parameter": [
                  {
                    "name": "coding",
                    "valueCoding": {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "code": "code1"
                    }
                  }
                ]
              }
            },
            {
              "name": "validation",
              "resource": {
                "resourceType": "Parameters",
                "parameter": [
                  {
                    "name": "coding",
                    "valueCoding": {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "code": "code2"
                    }
                  }
                ]
              }
            },
            {
              "name": "validation",
              "resource": {
                "resourceType": "Parameters",
                "parameter": [
                  {
                    "name": "coding",
                    "valueCoding": {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "code": "code3"
                    }
                  }
                ]
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "batch/batch-validate-response-bundle.json"

    # Simple use of the batch validate operation
    @operation:batch-validate
    Scenario: batch-validate-bad
      When Client validates a batch on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "tx-resource",
              "resource": {
                "resourceType": "ValueSet",
                "url": "urn:uuid:80458796-b204-4d17-ac1c-8443dd8cb35b",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "concept": [
                        {
                          "code": "code1"
                        },
                        {
                          "code": "code2"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "url", "valueUri": "urn:uuid:80458796-b204-4d17-ac1c-8443dd8cb35b" },
            { "name": "lenient-display-validation", "valueBoolean": "true" },
            {
              "name": "validation",
              "resource": {
                "resourceType": "Parameters",
                "parameter": [
                  {
                    "name": "coding",
                    "valueCoding": {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "code": "code1",
                      "display": "xx"
                    }
                  },
                  {
                    "name": "lenient-display-validation",
                    "valueBoolean": false
                  }
                ]
              }
            },
            {
              "name": "validation",
              "resource": {
                "resourceType": "Parameters",
                "parameter": [
                  {
                    "name": "codingX",
                    "valueCoding": {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "code": "code2",
                      "display": "xx"
                    }
                  }
                ]
              }
            },
            {
              "name": "validation",
              "resource": {
                "resourceType": "Parameters",
                "parameter": [
                  {
                    "name": "coding",
                    "valueCoding": {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "code": "code3",
                      "display": "xx"
                    }
                  }
                ]
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "batch/batch-validate-bad-response-bundle.json"
