# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at main).
# Suite "compare": 28 tests for a FHIR 5.0 server. Do not edit; re-run the generator.
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the pattern is the upstream expected-response
# file, which is a matchetype — fetched at run time and compared by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:compare @mode:tx.fhir.org
Feature: Terminology server — compare
  Tests for candidate new 'related' operation
  Upstream mode "tx.fhir.org": a server is expected to pass this suite only when it supports it.

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r5"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/main/tests/"
    And TxServer is given the resources:
      | resource                               |
      | simple/codesystem-simple.json          |
      | extensions/codesystem-extensions.json  |
      | simple/valueset-all.json               |
      | simple/valueset-active.json            |
      | simple/valueset-inactive.json          |
      | simple/valueset-enumerated.json        |
      | simple/valueset-enumerated-bad.json    |
      | simple/valueset-filter-isa.json        |
      | simple/valueset-filter-property.json   |
      | simple/valueset-filter-regex.json      |
      | simple/valueset-filter-regex2.json     |
      | simple/valueset-filter-regex-prop.json |

  Rule: ValueSet $compare

    # Checks that an all value is the same as itself
    @operation:compare
    Scenario: related-all
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "thisUrl", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-all" },
            { "name": "otherUrl", "valueCode": "http://hl7.org/fhir/test/ValueSet/simple-all" },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-all-response.json"

    # Checks that an all value is the same as itself, in the presence of the active flag = true
    @operation:compare
    Scenario: related-active
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "thisUrl", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-active" },
            { "name": "otherUrl", "valueCode": "http://hl7.org/fhir/test/ValueSet/simple-active" },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-active-response.json"

    # Checks that an all value is the same as itself, in the presence of the active flag = false
    @operation:compare
    Scenario: related-inactive
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "thisUrl", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-inactive" },
            { "name": "otherUrl", "valueCode": "http://hl7.org/fhir/test/ValueSet/simple-inactive" },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-inactive-response.json"

    # Checks that an all value is the same as itself, in the presence of an enumerated list
    @operation:compare
    Scenario: related-enumerated
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "thisUrl", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-enumerated" },
            { "name": "otherUrl", "valueCode": "http://hl7.org/fhir/test/ValueSet/simple-enumerated" },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-enumerated-response.json"

    # Checks that an all value is the same as itself, in the presence of an is-a filter
    @operation:compare
    Scenario: related-is-a
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "thisUrl", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-isa" },
            { "name": "otherUrl", "valueCode": "http://hl7.org/fhir/test/ValueSet/simple-filter-isa" },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-is-a-response.json"

    # Checks that an all value is the same as itself, in the presence of an regex filter
    @operation:compare
    Scenario: related-regex-1
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "thisUrl", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-regex" },
            { "name": "otherUrl", "valueCode": "http://hl7.org/fhir/test/ValueSet/simple-filter-regex" },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-regex-1-response.json"

    # Checks that an all value is the same as itself, in the presence of a property regex filter
    @operation:compare
    Scenario: related-regex-2
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "thisUrl", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-regex-prop" },
            { "name": "otherUrl", "valueCode": "http://hl7.org/fhir/test/ValueSet/simple-filter-regex-prop" },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-regex-2-response.json"

    # Checks that two enumerated value sets are the same (concept order is different)
    @operation:compare
    Scenario: related-lists
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "concept": [
                        {
                          "code": "code1"
                        },
                        {
                          "code": "code2"
                        },
                        {
                          "code": "code3"
                        },
                        {
                          "code": "code2a"
                        },
                        {
                          "code": "code2b"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "concept": [
                        {
                          "code": "code3"
                        },
                        {
                          "code": "code2b"
                        },
                        {
                          "code": "code2a"
                        },
                        {
                          "code": "code2"
                        },
                        {
                          "code": "code1"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-lists-response.json"

    # Checks that two enumerated value sets are related such that the other contains this
    @operation:compare
    Scenario: related-lists-more
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "concept": [
                        {
                          "code": "code1"
                        },
                        {
                          "code": "code2"
                        },
                        {
                          "code": "code3"
                        },
                        {
                          "code": "code2a"
                        },
                        {
                          "code": "code2b"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "concept": [
                        {
                          "code": "code3"
                        },
                        {
                          "code": "code2b"
                        },
                        {
                          "code": "code2a"
                        },
                        {
                          "code": "code1"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-lists-more-response.json"

    # Checks that two enumerated value sets are related such that this contains the other
    @operation:compare
    Scenario: related-lists-less
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "concept": [
                        {
                          "code": "code1"
                        },
                        {
                          "code": "code2"
                        },
                        {
                          "code": "code3"
                        },
                        {
                          "code": "code2b"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "concept": [
                        {
                          "code": "code3"
                        },
                        {
                          "code": "code2b"
                        },
                        {
                          "code": "code2a"
                        },
                        {
                          "code": "code2"
                        },
                        {
                          "code": "code1"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-lists-less-response.json"

    # Checks that two enumerated value sets are overlapping
    @operation:compare
    Scenario: related-lists-over
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "concept": [
                        {
                          "code": "code1"
                        },
                        {
                          "code": "code2"
                        },
                        {
                          "code": "code3"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "concept": [
                        {
                          "code": "code2"
                        },
                        {
                          "code": "code2b"
                        },
                        {
                          "code": "code2a"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-lists-over-response.json"

    # Checks that two enumerated value sets are the disjoint
    @operation:compare
    Scenario: related-lists-disj
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "concept": [
                        {
                          "code": "code1"
                        },
                        {
                          "code": "code2"
                        },
                        {
                          "code": "code3"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "concept": [
                        {
                          "code": "code2b"
                        },
                        {
                          "code": "code2a"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-lists-disj-response.json"

    # Checks that two valuesets that import the same entire code systems are identical
    @operation:compare
    Scenario: related-systems
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple"
                    },
                    {
                      "system": "http://hl7.org/fhir/data-absent-reasons"
                    },
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/extensions"
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-2",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/extensions"
                    },
                    {
                      "system": "http://hl7.org/fhir/data-absent-reasons"
                    },
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple"
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-systems-response.json"

    # Checks that two valuesets that import the same entire code systems are identical
    @operation:compare
    Scenario: related-systems-2
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple"
                    },
                    {
                      "system": "http://hl7.org/fhir/data-absent-reasons"
                    },
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/extensions"
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-2",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/extensions"
                    },
                    {
                      "system": "http://hl7.org/fhir/data-absent-reasons"
                    },
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple"
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-systems-response.json"

    # Checks that two valuesets that import the same entire code systems are identical
    @operation:compare
    Scenario: related-systems-less
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple"
                    },
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/extensions"
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-2",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/extensions"
                    },
                    {
                      "system": "http://hl7.org/fhir/data-absent-reasons"
                    },
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple"
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-systems-less-response.json"

    # Checks that two valuesets that import the same entire code systems are identical
    @operation:compare
    Scenario: related-systems-more
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple"
                    },
                    {
                      "system": "http://hl7.org/fhir/data-absent-reasons"
                    },
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/extensions"
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-2",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/extensions"
                    },
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple"
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-systems-more-response.json"

    # Checks that two valuesets that import the same entire code systems are identical
    @operation:compare
    Scenario: related-system-disj
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple"
                    },
                    {
                      "system": "http://hl7.org/fhir/data-absent-reasons"
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-2",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/extensions"
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-systems-disj-response.json"

    # Checks that two valuesets that import the same entire code systems are identical
    @operation:compare
    Scenario: related-system-over
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple"
                    },
                    {
                      "system": "http://hl7.org/fhir/data-absent-reasons"
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-2",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/extensions"
                    },
                    {
                      "system": "http://hl7.org/fhir/data-absent-reasons"
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-systems-over-response.json"

    # Checks that two valuesets that haev the same filters in different orders (as filters)
    @operation:compare
    Scenario: related-filters-1
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1x",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "code1"
                        },
                        {
                          "property": "concept",
                          "op": "regex",
                          "value": "code"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-2x",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "regex",
                          "value": "code"
                        },
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "code1"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-filters-1-response.json"

    # Checks that two valuesets that haev the same filters in different orders (as includes)
    @operation:compare
    Scenario: related-filters-2
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1x",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "code1"
                        }
                      ]
                    },
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/extension",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "code1"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-2x",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/extension",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "code1"
                        }
                      ]
                    },
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "code1"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-filters-2-response.json"

    # Checks that two valuesets that haev the same filters in different orders (as includes from the
    # same system)
    @operation:compare
    Scenario: related-filters-3
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1y",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "code1"
                        }
                      ]
                    },
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "code1"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-2y",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "code1"
                        }
                      ]
                    },
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "code1"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-filters-3-response.json"

    # Checks that two valuesets that have the same content with incompatible definitions are
    # considered the same
    @operation:compare
    Scenario: related-mixed-1
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1m",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "code2a"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-2m",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "concept": [
                        {
                          "code": "code2a"
                        },
                        {
                          "code": "code2aI"
                        },
                        {
                          "code": "code2aII"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-mixed-response.json"

    # Checks that two valuesets that have the same content with incompatible definitions are
    # considered the same
    @operation:compare
    Scenario: related-mixed-1-less
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1m",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "code2a"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-2m",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "concept": [
                        {
                          "code": "code2a"
                        },
                        {
                          "code": "code1"
                        },
                        {
                          "code": "code2aI"
                        },
                        {
                          "code": "code2aII"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-mixed-less-response.json"

    # Checks that two valuesets that have the same content with incompatible definitions are
    # considered the same
    @operation:compare
    Scenario: related-mixed-1-more
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1m",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "code2a"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-2m",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "concept": [
                        {
                          "code": "code2a"
                        },
                        {
                          "code": "code2aII"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-mixed-more-response.json"

    # Checks that two valuesets that have the same content with incompatible definitions are
    # considered the same
    @operation:compare
    Scenario: related-mixed-1-disj
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1m",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "code2a"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-2m",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "concept": [
                        {
                          "code": "code1"
                        },
                        {
                          "code": "code3"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-mixed-disj-response.json"

    # Checks that two valuesets that have the same content with incompatible definitions are
    # considered the same
    @operation:compare
    Scenario: related-mixed-1-over
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1m",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "code2a"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-2m",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "concept": [
                        {
                          "code": "code2a"
                        },
                        {
                          "code": "code1"
                        },
                        {
                          "code": "code2aII"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-mixed-over-response.json"

    # Checks that two valuesets that have the same content with incompatible definitions are
    # considered the same
    @operation:compare
    Scenario: related-filters-less
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1x",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "code2a"
                        },
                        {
                          "property": "concept",
                          "op": "regex",
                          "value": "code"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-2x",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "regex",
                          "value": "code"
                        },
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "code2"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-filters-less-response.json"

    # Checks that two valuesets that have the same content with incompatible definitions are
    # considered the same
    @operation:compare
    Scenario: related-filters-more
      When Client compares value sets on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "thisValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-1x",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "code2"
                        },
                        {
                          "property": "concept",
                          "op": "regex",
                          "value": "code(.)*"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            {
              "name": "otherValueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/list-2x",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "regex",
                          "value": "code(.)*"
                        },
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "code2a"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "diagnostics", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "related/simple-filters-more-response.json"
