# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at 5bf53a4adb4a522a34a037fc4f7e797eb2956830).
# Suite "deprecated": 11 tests for a FHIR 4.0 server. Do not edit; re-run the generator.
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the expected response is the upstream file,
# fetched at run time and compared as a matchetype by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:deprecated @mode:general
Feature: Terminology server — deprecated
  Testing Deprecated+Withdrawn warnings

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r4"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/5bf53a4adb4a522a34a037fc4f7e797eb2956830/tests/"
    And TxServer is given the resources:
      | resource                                |
      | deprecated/codesystem-deprecated.json   |
      | deprecated/valueset-withdrawn.json      |
      | deprecated/valueset-not-withdrawn.json  |
      | deprecated/codesystem-experimental.json |
      | deprecated/valueset-experimental.json   |
      | deprecated/codesystem-draft.json        |
      | deprecated/valueset-draft.json          |
      | deprecated/valueset-deprecating.json    |

  Rule: ValueSet $expand

    @operation:expand
    Scenario: withdrawn
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/withdrawn" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "deprecated/expand-withdrawn-response-valueSet.json"

    @operation:expand
    Scenario: not-withdrawn
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/not-withdrawn" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "deprecated/expand-not-withdrawn-response-valueSet.json"

    @operation:expand
    Scenario: experimental
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/experimental" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "deprecated/expand-experimental-response-valueSet.json"

    @operation:expand
    Scenario: draft
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/draft" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "deprecated/expand-draft-response-valueSet.json"

    # Deprecating a code in a valueset
    @operation:expand
    Scenario: vs-deprecation
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/deprecating" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "deprecated/expand-deprecating-response-valueSet.json"

  Rule: ValueSet $validate-code

    @operation:validate-code
    Scenario: withdrawn-validate
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/withdrawn" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "code1",
                "system": "http://hl7.org/fhir/test/CodeSystem/deprecated"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "deprecated/validate-withdrawn-response-parameters.json"

    @operation:validate-code
    Scenario: not-withdrawn-validate
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/not-withdrawn" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "code1",
                "system": "http://hl7.org/fhir/test/CodeSystem/deprecated"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "deprecated/validate-not-withdrawn-response-parameters.json"

    @operation:validate-code
    Scenario: experimental-validate
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/experimental" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "code1",
                "system": "http://hl7.org/fhir/test/CodeSystem/experimental"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "deprecated/validate-experimental-response-parameters.json"

    @operation:validate-code
    Scenario: draft-validate
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/draft" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "code1",
                "system": "http://hl7.org/fhir/test/CodeSystem/draft"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "deprecated/validate-draft-response-parameters.json"

    # Validating a code that has been deprecated in the value set using a deprecated extension
    @operation:validate-code
    Scenario: deprecating-validate
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/deprecating" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "code2",
                "system": "http://hl7.org/fhir/test/CodeSystem/draft"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "deprecated/validate-deprecating-response-parameters.json"

    # Validating a code that has been deprecated in the value set
    @operation:validate-code
    Scenario: deprecating-validate-2
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/deprecating" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "code3",
                "system": "http://hl7.org/fhir/test/CodeSystem/draft"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "deprecated/validate-deprecating-2-response-parameters.json"
