# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at main).
# Suite "default-valueset-version": 12 tests for a FHIR 4.0 server. Do not edit; re-run the generator.
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the pattern is the upstream expected-response
# file, which is a matchetype — fetched at run time and compared by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:default-valueset-version @mode:general
Feature: Terminology server — default-valueset-version
  Test the default-valueset-version parameter

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r4"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/main/tests/"
    And TxServer is given the resources:
      | resource                                     |
      | valueset-version/codesystem-vs-version.json  |
      | valueset-version/valueset-vs-version-a1.json |
      | valueset-version/valueset-vs-version-a2.json |
      | valueset-version/valueset-vs-version-b0.json |
      | valueset-version/valueset-vs-version-b1.json |
      | valueset-version/valueset-vs-version-b2.json |

  Rule: ValueSet $expand

    # Test the actual value set directly - v1
    @operation:expand
    Scenario: direct-expand-one
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/vs-version" },
            { "name": "valueSetVersion", "valueString": "1.0.0" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "valueset-version/expand-direct-expand-one-response-valueSet.json"

    # Test the actual value set directly - v2
    @operation:expand
    Scenario: direct-expand-two
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/vs-version" },
            { "name": "valueSetVersion", "valueString": "2.0.0" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "valueset-version/expand-direct-expand-two-response-valueSet.json"

    # Test the actual value set indirectly - v1
    @operation:expand
    Scenario: indirect-expand-one
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/vs-version-b1" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "valueset-version/expand-indirect-expand-one-response-valueSet.json"

    # Test the actual value set indirectly - v2
    @operation:expand
    Scenario: indirect-expand-two
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/vs-version-b2" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "valueset-version/expand-indirect-expand-two-response-valueSet.json"

    # Test the actual value set indirectly - versionless
    @operation:expand
    Scenario: indirect-expand-zero
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/vs-version-b0" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "valueset-version/expand-indirect-expand-zero-response-valueSet.json"

    # Test the actual value set indirectly - versionless, and specify a version
    @operation:expand
    Scenario: indirect-expand-zero-pinned
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/vs-version-b0" },
            {
              "name": "default-valueset-version",
              "valueCanonical": "http://hl7.org/fhir/test/ValueSet/vs-version|1.0.0"
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "valueset-version/expand-indirect-expand-zero-pinned-response-valueSet.json"

    # Test the actual value set indirectly - versionless, and specify a version that doesn't exist
    @operation:expand @http-code:4xx
    Scenario: indirect-expand-zero-pinned-wrong
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/vs-version-b0" },
            {
              "name": "default-valueset-version",
              "valueCanonical": "http://hl7.org/fhir/test/ValueSet/vs-version|3.0.0"
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the pattern in "valueset-version/expand-indirect-expand-zero-pinned-wrong-response-outcome.json"

  Rule: ValueSet $validate-code

    # Test the value set indirectly
    @operation:validate-code
    Scenario: indirect-validation-one
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/vs-version-b1" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/vs-version",
                "code": "code2"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "valueset-version/coding-indirect-one-response-parameters.json"

    # Test the value set indirectly
    @operation:validate-code
    Scenario: indirect-validation-two
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/vs-version-b2" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/vs-version",
                "code": "code2"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "valueset-version/coding-indirect-two-response-parameters.json"

    # Test the value set indirectly
    @operation:validate-code
    Scenario: indirect-validation-zero
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/vs-version-b0" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/vs-version",
                "code": "code2"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "valueset-version/coding-indirect-zero-response-parameters.json"

    # Test the value set indirectly
    @operation:validate-code
    Scenario: indirect-validation-zero-pinned
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/vs-version-b0" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/vs-version",
                "code": "code2"
              }
            },
            {
              "name": "default-valueset-version",
              "valueCanonical": "http://hl7.org/fhir/test/ValueSet/vs-version|1.0.0"
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "valueset-version/coding-indirect-zero-pinned-response-parameters.json"

    # Test the value set indirectly
    @operation:validate-code
    Scenario: indirect-validation-zero-pinned-wrong
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/vs-version-b0" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/vs-version",
                "code": "code2"
              }
            },
            {
              "name": "default-valueset-version",
              "valueCanonical": "http://hl7.org/fhir/test/ValueSet/vs-version|3.0.0"
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "valueset-version/coding-indirect-zero-pinned-wrong-response-parameters.json"
