# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at 5bf53a4adb4a522a34a037fc4f7e797eb2956830).
# Suite "extensions": 12 tests for a FHIR 4.0 server. Do not edit; re-run the generator.
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the expected response is the upstream file,
# fetched at run time and compared as a matchetype by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:extensions @mode:general
Feature: Terminology server — extensions
  Testing proper handling of extensions, which depends on the extension

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r4"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/5bf53a4adb4a522a34a037fc4f7e797eb2956830/tests/"
    And TxServer is given the resources:
      | resource                                           |
      | extensions/codesystem-extensions.json              |
      | extensions/codesystem-supplement.json              |
      | extensions/valueset-extensions-all.json            |
      | extensions/valueset-extensions-bad-supplement.json |
      | extensions/valueset-extensions-enumerated.json     |

  Rule: ValueSet $expand

    @operation:expand
    Scenario: extensions-echo-all
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/extensions-all" },
            { "name": "includeDesignations", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "extensions/expand-echo-all-valueset.json"

    @operation:expand
    Scenario: extensions-echo-enumerated
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/extensions-enumerated" },
            { "name": "includeDesignations", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "extensions/expand-echo-enumerated-valueset.json"

    @operation:expand @http-code:4xx
    Scenario: extensions-echo-bad-supplement
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/extensions-bad-supplement" },
            { "name": "includeDesignations", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the expected response "extensions/expand-echo-bad-supplement-outcome.json"

  Rule: ValueSet $validate-code

    @operation:validate-code @http-code:4xx
    Scenario: validate-code-bad-supplement
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/extensions-bad-supplement" },
            { "name": "code", "valueCode": "code1" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/extensions" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the expected response "extensions/validate-code-bad-supplement-response-outcome.json"

    @operation:validate-code @http-code:4xx
    Scenario: validate-coding-bad-supplement
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/extensions-bad-supplement" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/extensions",
                "code": "code1"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the expected response "extensions/validate-coding-bad-supplement-response-outcome.json"

    @operation:validate-code @http-code:4xx
    Scenario: validate-codeableconcept-bad-supplement
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/extensions-bad-supplement" },
            {
              "name": "codeableConcept",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/test/CodeSystem/extensions",
                    "code": "code1"
                  }
                ]
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the expected response "extensions/validate-codeableconcept-bad-supplement-response-outcome.json"

    @operation:validate-code
    Scenario: validate-coding-good-supplement
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/extensions-enumerated" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/extensions",
                "code": "code1",
                "display": "ectenoot"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "extensions/validate-coding-good-supplement-response-parameters.json"

    @operation:validate-code
    Scenario: validate-coding-good2-supplement
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/extensions-enumerated" },
            { "name": "displayLanguage", "valueCode": "nl" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/extensions",
                "code": "code1",
                "display": "ectenoot"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "extensions/validate-coding-good2-supplement-response-parameters.json"

  Rule: CodeSystem $validate-code

    @operation:cs-validate-code @http-code:2xx
    Scenario: validate-coding-bad-supplement-url
      When Client validates a code against the code system on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/supplement",
                "code": "code1"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^2"
      And $response should match the expected response "extensions/validate-coding-bad-supplement-url-response-outcome.json"

    # Check handling of a deprecated designation (lenient display validation)
    @operation:cs-validate-code
    Scenario: validate-code-inactive-display-lenient
      When Client validates a code against the code system on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "code", "valueCode": "code2" },
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/CodeSystem/extensions" },
            { "name": "display", "valueString": "2nd Code" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" },
            { "name": "lenient-display-validation", "valueBoolean": true }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "extensions/validate-code-inactive-display-lenient-response-outcome.json"

    # Check handling of a deprecated designation (strict display validation)
    @operation:cs-validate-code
    Scenario: validate-code-inactive-display-notlenient
      When Client validates a code against the code system on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "code", "valueCode": "code2" },
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/CodeSystem/extensions" },
            { "name": "display", "valueString": "2nd Code" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" },
            { "name": "lenient-display-validation", "valueBoolean": false }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "extensions/validate-code-inactive-display-not-lenient-response-outcome.json"

    # Check handling of a deprecated concept
    @operation:cs-validate-code
    Scenario: validate-code-inactive
      When Client validates a code against the code system on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "code", "valueCode": "code5" },
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/CodeSystem/extensions" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "extensions/validate-code-inactive-response-outcome.json"
