# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at main).
# Suite "errors": 7 tests for a FHIR 5.0 server. Do not edit; re-run the generator.
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the pattern is the upstream expected-response
# file, which is a matchetype — fetched at run time and compared by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:errors @mode:general
Feature: Terminology server — errors
  Testing Various Error Conditions

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r5"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/main/tests/"
    And TxServer is given the resources:
      | resource                            |
      | simple/codesystem-simple.json       |
      | errors/valueset-unknown-system.json |
      | errors/valueset-broken-filter.json  |
      | errors/valueset-broken-filter2.json |
      | errors/cs1.json                     |
      | errors/cs2.json                     |
      | errors/valueset-combination.json    |

  Rule: ValueSet $validate-code

    # Value set & request refers to an unknown system
    @operation:validate-code
    Scenario: unknown-system1
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/unknown-system" },
            { "name": "code", "valueCode": "code1" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/simpleX" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "errors/errors-unknown-system1-response.json"

    # Value set & request refers to an unknown system; request is a different unknown system
    @operation:validate-code
    Scenario: unknown-system2
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/unknown-system" },
            { "name": "code", "valueCode": "code1" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/simpleXX" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "errors/errors-unknown-system2-response.json"

    # Make sure that filters without value cause an error
    @operation:validate-code @http-code:4xx
    Scenario: broken-filter-validate
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/broken-filter" },
            { "name": "code", "valueCode": "code1" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/simple" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the pattern in "errors/errors-broken-filter-validate-response.json"

    # Make sure that filters without value cause an error (extension only)
    @operation:validate-code @http-code:4xx
    Scenario: broken-filter2-validate
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/broken-filter2" },
            { "name": "code", "valueCode": "code1" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/simple" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the pattern in "errors/errors-broken-filter2-validate-response.json"

    # A value set that contains two identical codes - validates ok
    @operation:validate-code
    Scenario: combination-ok
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/combination" },
            { "name": "code", "valueCode": "code1" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/simple1" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "errors/errors-combination-ok-response.json"

    # A value set that contains two identical codes - error if inferSystem is true
    @operation:validate-code
    Scenario: combination-bad
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/combination" },
            { "name": "code", "valueCode": "code1" },
            { "name": "inferSystem", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "errors/errors-combination-bad-response.json"

  Rule: ValueSet $expand

    # Make sure that filters without value cause an error
    @operation:expand @http-code:4xx
    Scenario: broken-filter-expand
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/broken-filter" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the pattern in "errors/errors-broken-filter-expand-response.json"
