# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at main).
# Suite "fragment": 7 tests for a FHIR 4.0 server. Do not edit; re-run the generator.
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the expected response is the upstream file,
# fetched at run time and compared as a matchetype by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:fragment @mode:general
Feature: Terminology server — fragment
  Testing handling a code system fragment

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r4"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/main/tests/"
    And TxServer is given the resources:
      | resource                          |
      | fragment/codesystem-fragment.json |
      | fragment/valueset-fragment.json   |

  Rule: ValueSet $expand

    # check that the fragment is reported correctly
    @operation:expand
    Scenario: fragment-expansion
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/fragment" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "fragment/fragment-expand-response.json"

  Rule: ValueSet $validate-code

    # if a code is a in a fragment, then it's all ok
    @operation:validate-code
    Scenario: validation-fragment-code-good
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/fragment" },
            { "name": "code", "valueCode": "code1" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/fragment" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "fragment/fragment-code-good-response-parameters.json"

    # if a code is a in a fragment, then it's all ok
    @operation:validate-code
    Scenario: validation-fragment-coding-good
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/fragment" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/fragment",
                "code": "code1"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "fragment/fragment-coding-good-response-parameters.json"

    # if a code is a in a fragment, then it's all ok
    @operation:validate-code
    Scenario: validation-fragment-codeableconcept-good
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/fragment" },
            {
              "name": "codeableConcept",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/test/CodeSystem/fragment",
                    "code": "code1"
                  }
                ]
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "fragment/fragment-codeableconcept-good-response-parameters.json"

    # if a code is not in the fragment, we can't call it invalid (code variant)
    @operation:validate-code
    Scenario: validation-fragment-code-bad-code
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/fragment" },
            { "name": "code", "valueCode": "code1x" },
            { "name": "system", "valueCanonical": "http://hl7.org/fhir/test/CodeSystem/fragment" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "fragment/fragment-code-bad-code-response-parameters.json"

    # if a code is not in the fragment, we can't call it invalid (coding variant)
    @operation:validate-code
    Scenario: validation-fragment-coding-bad-code
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/fragment" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/fragment",
                "code": "code1x"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "fragment/fragment-coding-bad-code-response-parameters.json"

    # if a code is not in the fragment, we can't call it invalid (CodeableConcept variant)
    @operation:validate-code
    Scenario: validation-fragment-codeableconcept-bad-code
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/fragment" },
            {
              "name": "codeableConcept",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/test/CodeSystem/fragment",
                    "code": "code1x"
                  }
                ]
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "fragment/fragment-codeableconcept-bad-code-response-parameters.json"
