# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at main).
# Suite "inactive": 12 tests for a FHIR 4.0 server. Do not edit; re-run the generator.
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the pattern is the upstream expected-response
# file, which is a matchetype — fetched at run time and compared by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:inactive @mode:general
Feature: Terminology server — inactive
  Testing Inactive codes

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r4"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/main/tests/"
    And TxServer is given the resources:
      | resource                            |
      | inactive/codesystem-inactive.json   |
      | inactive/valueset-all.json          |
      | inactive/valueset-all-inactive.json |
      | inactive/valueset-all-active.json   |

  Rule: ValueSet $expand

    @operation:expand
    Scenario: inactive-expand
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/inactive-all" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "inactive/inactive-expand-all-response-valueSet.json"

    @operation:expand
    Scenario: inactive-inactive-expand
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/inactive-all-inactive" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "inactive/inactive-inactive-expand-all-response-valueSet.json"

    @operation:expand
    Scenario: inactive-active-expand
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/inactive-all-active" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "inactive/inactive-active-expand-all-response-valueSet.json"

  Rule: ValueSet $validate-code

    @operation:validate-code
    Scenario: inactive-1-validate
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/inactive-all" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeActive",
                "system": "http://hl7.org/fhir/test/CodeSystem/inactive"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "inactive/validate-inactive-1-response-parameters.json"

    @operation:validate-code
    Scenario: inactive-2-validate
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/inactive-all" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeInactive",
                "system": "http://hl7.org/fhir/test/CodeSystem/inactive"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "inactive/validate-inactive-2-response-parameters.json"

    @operation:validate-code
    Scenario: inactive-3-validate
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/inactive-all" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeRetired",
                "system": "http://hl7.org/fhir/test/CodeSystem/inactive"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "inactive/validate-inactive-3-response-parameters.json"

    @operation:validate-code
    Scenario: inactive-1a-validate
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/inactive-all-active" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeActive",
                "system": "http://hl7.org/fhir/test/CodeSystem/inactive"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "inactive/validate-inactive-1a-response-parameters.json"

    @operation:validate-code
    Scenario: inactive-2a-validate
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/inactive-all-active" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeInactive",
                "system": "http://hl7.org/fhir/test/CodeSystem/inactive"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "inactive/validate-inactive-2a-response-parameters.json"

    @operation:validate-code
    Scenario: inactive-3a-validate
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/inactive-all-active" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeRetired",
                "system": "http://hl7.org/fhir/test/CodeSystem/inactive"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "inactive/validate-inactive-3a-response-parameters.json"

    @operation:validate-code
    Scenario: inactive-1b-validate
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/inactive-all-inactive" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeActive",
                "system": "http://hl7.org/fhir/test/CodeSystem/inactive"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "inactive/validate-inactive-1b-response-parameters.json"

    @operation:validate-code
    Scenario: inactive-2b-validate
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/inactive-all-inactive" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeInactive",
                "system": "http://hl7.org/fhir/test/CodeSystem/inactive"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "inactive/validate-inactive-2b-response-parameters.json"

    @operation:validate-code
    Scenario: inactive-3b-validate
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/inactive-all-inactive" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeRetired",
                "system": "http://hl7.org/fhir/test/CodeSystem/inactive"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "inactive/validate-inactive-3b-response-parameters.json"
