# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at main).
# Suite "language2": 25 tests for a FHIR 4.0 server. Do not edit; re-run the generator.
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the expected response is the upstream file,
# fetched at run time and compared as a matchetype by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:language2 @mode:general
Feature: Terminology server — language2
  A series of tests that test display name validation for various permutations of languages
  see display/index.md for an explanation

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r4"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/main/tests/"
    And TxServer is given the resources:
      | resource                       |
      | display/codesystem-en.json     |
      | display/codesystem-ende-N.json |
      | display/codesystem-ende.json   |
      | display/codesystem-none.json   |
      | display/valueset-en.json       |
      | display/valueset-ende-N.json   |
      | display/valueset-ende.json     |
      | display/valueset-none.json     |

  Rule: ValueSet $validate-code

    @operation:validate-code
    Scenario: validation-right-de-en
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-en" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-en",
                "display": "Code1",
                "code": "code1"
              }
            },
            { "name": "displayLanguage", "valueCode": "de" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-right-de-en-response-parameters.json"

    @operation:validate-code
    Scenario: validation-right-de-ende-N
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-ende-N" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-ende-N",
                "display": "Code1",
                "code": "code1"
              }
            },
            { "name": "displayLanguage", "valueCode": "de" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-right-de-ende-N-response-parameters.json"

    @operation:validate-code
    Scenario: validation-right-de-ende
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-ende" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-ende",
                "display": "Anzeige1",
                "code": "code1"
              }
            },
            { "name": "displayLanguage", "valueCode": "de" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-right-de-ende-response-parameters.json"

    @operation:validate-code
    Scenario: validation-right-de-none
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-none" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-none",
                "display": "Code1",
                "code": "code1"
              }
            },
            { "name": "displayLanguage", "valueCode": "de" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-right-de-none-response-parameters.json"

    @operation:validate-code
    Scenario: validation-right-en-en
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-en" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-en",
                "display": "Code1",
                "code": "code1"
              }
            },
            { "name": "displayLanguage", "valueCode": "en" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-right-en-en-response-parameters.json"

    @operation:validate-code
    Scenario: validation-right-en-ende-N
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-ende-N" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-ende-N",
                "display": "Code1",
                "code": "code1"
              }
            },
            { "name": "displayLanguage", "valueCode": "en" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-right-en-ende-N-response-parameters.json"

    @operation:validate-code
    Scenario: validation-right-en-ende
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-ende" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-ende",
                "display": "Code1",
                "code": "code1"
              }
            },
            { "name": "displayLanguage", "valueCode": "en" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-right-en-ende-response-parameters.json"

    @operation:validate-code
    Scenario: validation-right-en-none
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-none" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-none",
                "display": "Code1",
                "code": "code1"
              }
            },
            { "name": "displayLanguage", "valueCode": "en" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-right-en-none-response-parameters.json"

    @operation:validate-code
    Scenario: validation-right-none-en
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-en" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-en",
                "display": "Code1",
                "code": "code1"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-right-none-en-response-parameters.json"

    @operation:validate-code
    Scenario: validation-right-none-ende-N
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-ende-N" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-ende-N",
                "display": "Code1",
                "code": "code1"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-right-none-ende-N-response-parameters.json"

    @operation:validate-code
    Scenario: validation-right-none-ende
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-ende" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-ende",
                "display": "Code1",
                "code": "code1"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-right-none-ende-response-parameters.json"

    @operation:validate-code
    Scenario: validation-right-none-none
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-none" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-none",
                "display": "Code1",
                "code": "code1"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-right-none-none-response-parameters.json"

    @operation:validate-code
    Scenario: validation-wrong-de-en
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-en" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-en",
                "display": "XCode1",
                "code": "code1"
              }
            },
            { "name": "displayLanguage", "valueCode": "de" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-wrong-de-en-response-parameters.json"

    # Same request, but with an invalid displayName parameter
    @operation:validate-code @http-code:4xx
    Scenario: validation-wrong-de-en-bad
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-en" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-en",
                "display": "XCode1",
                "code": "code1"
              }
            },
            { "name": "displayLanguage", "valueCode": "-" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the expected response "display/validation-wrong-de-en-bad-response-outcome.json"

    @operation:validate-code
    Scenario: validation-wrong-de-ende-N
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-ende-N" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-ende-N",
                "display": "XCode1",
                "code": "code1"
              }
            },
            { "name": "displayLanguage", "valueCode": "de" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-wrong-de-ende-N-response-parameters.json"

    @operation:validate-code
    Scenario: validation-wrong-de-ende
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-ende" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-ende",
                "display": "XCode1",
                "code": "code1"
              }
            },
            { "name": "displayLanguage", "valueCode": "de" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-wrong-de-ende-response-parameters.json"

    @operation:validate-code
    Scenario: validation-wrong-de-none
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-none" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-none",
                "display": "XCode1",
                "code": "code1"
              }
            },
            { "name": "displayLanguage", "valueCode": "de" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-wrong-de-none-response-parameters.json"

    @operation:validate-code
    Scenario: validation-wrong-en-en
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-en" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-en",
                "display": "XCode1",
                "code": "code1"
              }
            },
            { "name": "displayLanguage", "valueCode": "en" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-wrong-en-en-response-parameters.json"

    @operation:validate-code
    Scenario: validation-wrong-en-ende-N
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-ende-N" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-ende-N",
                "display": "XCode1",
                "code": "code1"
              }
            },
            { "name": "displayLanguage", "valueCode": "en" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-wrong-en-ende-N-response-parameters.json"

    @operation:validate-code
    Scenario: validation-wrong-en-ende
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-ende" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-ende",
                "display": "XCode1",
                "code": "code1"
              }
            },
            { "name": "displayLanguage", "valueCode": "en" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-wrong-en-ende-response-parameters.json"

    @operation:validate-code
    Scenario: validation-wrong-en-none
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-none" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-none",
                "display": "XCode1",
                "code": "code1"
              }
            },
            { "name": "displayLanguage", "valueCode": "en" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-wrong-en-none-response-parameters.json"

    @operation:validate-code
    Scenario: validation-wrong-none-en
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-en" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-en",
                "display": "XCode1",
                "code": "code1"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-wrong-none-en-response-parameters.json"

    @operation:validate-code
    Scenario: validation-wrong-none-ende-N
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-ende-N" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-ende-N",
                "display": "XCode1",
                "code": "code1"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-wrong-none-ende-N-response-parameters.json"

    @operation:validate-code
    Scenario: validation-wrong-none-ende
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-ende" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-ende",
                "display": "XCode1",
                "code": "code1"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-wrong-none-ende-response-parameters.json"

    @operation:validate-code
    Scenario: validation-wrong-none-none
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/lang-none" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/lang-none",
                "display": "XCode1",
                "code": "code1"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "display/validation-wrong-none-none-response-parameters.json"
