# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at main).
# Suite "metadata": 2 tests for a FHIR 4.0 server. Do not edit; re-run the generator.
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the expected response is the upstream file,
# fetched at run time and compared as a matchetype by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:metadata
Feature: Terminology server — metadata
  tests for minimal requirements for metadata statements
  These tests apply to all servers

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r4"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/main/tests/"

  Rule: Capability statement

    # Check that the minimum expected things are found in the server CapabilityStatement
    @operation:metadata
    Scenario: metadata
      When Client reads the capability statement of TxServer as $capabilities
      Then $response.status should be 200
      And $capabilities should match the expected response "capstmt.json"

  Rule: Terminology capabilities

    # Check that the minimum expected things are found in the server TerminologyCapabilities
    @operation:term-caps
    Scenario: term-caps
      When Client reads the terminology capabilities of TxServer as $capabilities
      Then $response.status should be 200
      And $capabilities should match the expected response "capterms.json"
