# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at main).
# Suite "notSelectable": 50 tests for a FHIR 4.0 server. Do not edit; re-run the generator.
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the pattern is the upstream expected-response
# file, which is a matchetype — fetched at run time and compared by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:notSelectable @mode:general
Feature: Terminology server — notSelectable
  Testing notSelectable

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r4"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/main/tests/"
    And TxServer is given the resources:
      | resource                                               |
      | notSelectable/codesystem-notSelectable-prop.json       |
      | notSelectable/valueset-notSelectable-prop-all.json     |
      | notSelectable/valueset-notSelectable-prop-false.json   |
      | notSelectable/valueset-notSelectable-prop-true.json    |
      | notSelectable/valueset-notSelectable-prop-trueUC.json  |
      | notSelectable/valueset-notSelectable-prop-in.json      |
      | notSelectable/valueset-notSelectable-prop-out.json     |
      | notSelectable/codesystem-notSelectable-noprop.json     |
      | notSelectable/valueset-notSelectable-noprop-all.json   |
      | notSelectable/valueset-notSelectable-noprop-false.json |
      | notSelectable/valueset-notSelectable-noprop-true.json  |
      | notSelectable/codesystem-notSelectable-reprop.json     |
      | notSelectable/valueset-notSelectable-reprop-all.json   |
      | notSelectable/valueset-notSelectable-reprop-false.json |
      | notSelectable/valueset-notSelectable-reprop-true.json  |
      | notSelectable/codesystem-notSelectable-unprop.json     |
      | notSelectable/valueset-notSelectable-unprop-all.json   |
      | notSelectable/valueset-notSelectable-unprop-false.json |
      | notSelectable/valueset-notSelectable-unprop-true.json  |

  Rule: ValueSet $expand

    @operation:expand
    Scenario: notSelectable-prop-all
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-all" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/expand-prop-all-response-valueSet.json"

    @operation:expand
    Scenario: notSelectable-noprop-all
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-noprop-all" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/expand-noprop-all-response-valueSet.json"

    @operation:expand
    Scenario: notSelectable-reprop-all
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-reprop-all" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/expand-reprop-all-response-valueSet.json"

    @operation:expand
    Scenario: notSelectable-unprop-all
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-reprop-all" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/expand-reprop-all-response-valueSet.json"

    @operation:expand
    Scenario: notSelectable-prop-true
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-true" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/expand-prop-true-response-valueSet.json"

    @operation:expand
    Scenario: notSelectable-prop-trueUC
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-trueUC" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/expand-prop-trueUC-response-valueSet.json"

    @operation:expand
    Scenario: notSelectable-noprop-true
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-noprop-true" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/expand-noprop-true-response-valueSet.json"

    @operation:expand
    Scenario: notSelectable-reprop-true
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-reprop-true" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/expand-reprop-true-response-valueSet.json"

    @operation:expand
    Scenario: notSelectable-unprop-true
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-unprop-true" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/expand-unprop-true-response-valueSet.json"

    @operation:expand
    Scenario: notSelectable-prop-false
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-false" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/expand-prop-false-response-valueSet.json"

    @operation:expand
    Scenario: notSelectable-noprop-false
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-noprop-false" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/expand-noprop-false-response-valueSet.json"

    @operation:expand
    Scenario: notSelectable-reprop-false
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-reprop-false" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/expand-reprop-false-response-valueSet.json"

    @operation:expand
    Scenario: notSelectable-unprop-false
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-unprop-false" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/expand-unprop-false-response-valueSet.json"

    @operation:expand
    Scenario: notSelectable-prop-in
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-in" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/expand-prop-in-response-valueSet.json"

    @operation:expand
    Scenario: notSelectable-prop-out
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-out" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/expand-prop-out-response-valueSet.json"

  Rule: ValueSet $validate-code

    @operation:validate-code
    Scenario: notSelectable-prop-true-true
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-true" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeNS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-prop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-prop-true-true-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-prop-trueUC-true
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-trueUC" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeNS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-prop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-prop-trueUC-true-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-prop-in-true
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-in" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeNS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-prop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-prop-in-true-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-prop-out-true
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-out" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeNS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-prop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-prop-out-true-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-noprop-true-true
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-noprop-true" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeNS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-noprop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-noprop-true-true-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-reprop-true-true
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-reprop-true" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeNS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-reprop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-reprop-true-true-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-unprop-true-true
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-unprop-true" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeNS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-unprop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-unprop-true-true-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-prop-true-false
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-true" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-prop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-prop-true-false-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-prop-in-false
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-in" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-prop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-prop-in-false-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-prop-in-unknown
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-in" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeU",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-prop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-prop-in-unknown-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-prop-out-unknown
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-out" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeU",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-prop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-prop-out-unknown-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-prop-out-false
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-out" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-prop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-prop-out-false-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-noprop-true-false
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-noprop-true" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-noprop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-noprop-true-false-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-reprop-true-false
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-reprop-true" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-reprop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-reprop-true-false-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-unprop-true-false
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-unprop-true" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-unprop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-unprop-true-false-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-prop-false-true
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-false" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeNS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-prop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-prop-false-true-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-noprop-false-true
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-noprop-false" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeNS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-noprop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-noprop-false-true-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-reprop-false-true
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-reprop-false" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeNS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-reprop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-reprop-false-true-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-unprop-false-true
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-unprop-false" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeNS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-unprop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-unprop-false-true-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-prop-false-false
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-false" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-prop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-prop-false-false-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-noprop-false-false
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-noprop-false" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-noprop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-noprop-false-false-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-reprop-false-false
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-reprop-false" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-reprop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-reprop-false-false-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-unprop-false-false
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-unprop-false" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-unprop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-unprop-false-false-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-noprop-true-unknown
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-noprop-true" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeU",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-noprop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-noprop-true-unknown-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-reprop-true-unknown
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-reprop-true" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeU",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-reprop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-reprop-true-unknown-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-unprop-true-unknown
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-unprop-true" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeU",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-unprop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-unprop-true-unknown-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-prop-true-unknown
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-true" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeU",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-prop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-prop-true-unknown-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-prop-false-unknown
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-false" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeU",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-prop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-prop-false-unknown-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-noprop-false-unknown
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-noprop-false" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeU",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-noprop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-noprop-false-unknown-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-reprop-false-unknown
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-reprop-false" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeU",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-reprop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-reprop-false-unknown-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-unprop-false-unknown
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-unprop-false" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeU",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-unprop"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-unprop-false-unknown-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-prop-true-true-param-true
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-true" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeNS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-prop"
              }
            },
            { "name": "abstract", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-prop-true-true-param-true-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-prop-true-true-param-false
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-true" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeNS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-prop"
              }
            },
            { "name": "abstract", "valueBoolean": false },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-prop-true-true-param-false-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-prop-false-false-param-true
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-false" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-prop"
              }
            },
            { "name": "abstract", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-prop-false-false-param-true-response-parameters.json"

    @operation:validate-code
    Scenario: notSelectable-prop-false-false-param-false
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/notSelectable-prop-false" },
            {
              "name": "coding",
              "valueCoding": {
                "code": "codeS",
                "system": "http://hl7.org/fhir/test/CodeSystem/notSelectable-prop"
              }
            },
            { "name": "abstract", "valueBoolean": false },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "notSelectable/validate-prop-false-false-param-false-response-parameters.json"
