# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at main).
# Suite "overload": 29 tests for a FHIR 5.0 server. Do not edit; re-run the generator.
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the pattern is the upstream expected-response
# file, which is a matchetype — fetched at run time and compared by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:overload @mode:general
Feature: Terminology server — overload
  A set of tests that test out handling of value sets that cross versions of the same code system

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r5"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/main/tests/"
    And TxServer is given the resources:
      | resource                                          |
      | overload/codesystem-overload-1.json               |
      | overload/codesystem-overload-2.json               |
      | overload/valueset-overload-all.json               |
      | overload/valueset-overload-all-versioned.json     |
      | overload/valueset-overload-all-merged.json        |
      | overload/valueset-overload-exclude.json           |
      | overload/valueset-overload-exclude-versioned.json |
      | overload/valueset-overload-exclude-merged.json    |
      | overload/valueset-overload-enum-good.json         |
      | overload/valueset-overload-enum-bad.json          |
      | overload/valueset-overload-exclude-enum.json      |
      | overload/valueset-overload-mixed.json             |

  Rule: ValueSet $expand

    # Expanding two versions of the same code system
    @operation:expand
    Scenario: expand-all
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-all" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/overload-expand-all-response.json"

    # Expanding two versions of the same code system, versioned
    @operation:expand
    Scenario: expand-all-versioned
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-all-versioned" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/overload-expand-all-versioned-response.json"

    # Expanding two versions of the same code system, merging versions
    @operation:expand
    Scenario: expand-all-merged
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-all-merged" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/overload-expand-all-merged-response.json"

    # Expanding two versions of the same code system, codes selected from each version
    @operation:expand
    Scenario: expand-enum-good
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-enum-good" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/overload-expand-enum-good-response.json"

    # Expanding two versions of the same code system, codes selected from both versions - but you
    # can't do this
    @operation:expand
    Scenario: expand-enum-bad
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-enum-bad" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/overload-expand-enum-bad-response.json"

    # Excluding one version of the code system from the other (cheap diff analysis)
    @operation:expand
    Scenario: expand-exclude
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-exclude" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/overload-expand-exclude-response.json"

    # Excluding one version of the code system from the other (cheap diff analysis), versioned
    @operation:expand
    Scenario: expand-exclude-versioned
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-exclude-versioned" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/overload-expand-exclude-versioned-response.json"

    # Excluding one version of the code system from the other (cheap diff analysis), merging versions
    @operation:expand
    Scenario: expand-exclude-merged
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-exclude-merged" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/overload-expand-exclude-merged-response.json"

    # Tests whether a system-version parameter forcing v1 overrides the value set's explicit
    # dual-version includes. It should not, since it's just a default
    @operation:expand
    Scenario: expand-all-sysver
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-all" },
            { "name": "system-version", "valueCanonical": "http://hl7.org/fhir/test/CodeSystem/overload|1.0.0" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/overload-expand-all-sysver-response.json"

    # Expands a value set that includes all of both versions but excludes only code2 from v1 by
    # enumeration, testing version-scoped exclusion of individual codes.
    @operation:expand
    Scenario: expand-exclude-enum
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-exclude-enum" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/overload-expand-exclude-enum-response.json"

    # Expands a value set with one versioned include (v1) and one unversioned include, testing how the
    # server resolves the unversioned reference.
    @operation:expand
    Scenario: expand-mixed
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-mixed" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/overload-expand-mixed-response.json"

  Rule: ValueSet $validate-code

    # Is code in value set - in both versions
    @operation:validate-code
    Scenario: validate-all-good
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-all" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/overload",
                "code": "code1"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/validate-good-response.json"

    # Is code in value set - in both versions, but display from the second
    @operation:validate-code
    Scenario: validate-all-good2
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-all" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/overload",
                "code": "code2",
                "display": "Display #2"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/validate-good2-response.json"

    # Is code in value set - in one version
    @operation:validate-code
    Scenario: validate-all-good3
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-all" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/overload",
                "code": "code3"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/validate-good3-response.json"

    # Is code in value set - in one versions
    @operation:validate-code
    Scenario: validate-all-good4
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-all" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/overload",
                "code": "code4"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/validate-good4-response.json"

    # Is code in value set - in one versions
    @operation:validate-code
    Scenario: validate-all-bad2
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-all" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/overload",
                "code": "code2",
                "display": "Display Two"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/validate-bad2-response.json"

    # code from one version, display from the other
    @operation:validate-code
    Scenario: validate-all-bad2v
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-all" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/overload",
                "code": "code2",
                "version": "2.0.0",
                "display": "Display 2"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/validate-bad2v-response.json"

    # Validates that code1 is rejected by the enum-good value set, since it's not in the enumerated
    # list.
    @operation:validate-code
    Scenario: validate-bad-enum-code1
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-enum-good" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/overload",
                "code": "code1"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/validate-bad-enum-code1-response.json"

    # Validates that code1 is rejected by the exclude value set, since it exists in both versions and
    # the v1 overlap is excluded.
    @operation:validate-code
    Scenario: validate-bad-exclude-code1
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-exclude" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/overload",
                "code": "code1"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/validate-bad-exclude-code1-response.json"

    # Validates that a completely nonexistent code (code99) fails against the value set.
    @operation:validate-code
    Scenario: validate-bad-unknown
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-all" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/overload",
                "code": "code99"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/validate-bad-unknown-response.json"

    # Validates that code1 with version pinned to 1.0.0 succeeds, confirming version-pinning works for
    # a code present in both versions
    @operation:validate-code
    Scenario: validate-v1code2-wrongdisplay
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-all" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/overload",
                "version": "1.0.0",
                "code": "code2",
                "display": "Display #2"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/validate-bad-v1code2-wrongdisplay-response.json"

    # Validates that code4 with version explicitly pinned to 1.0.0 fails, since code4 only exists in
    # v2.
    @operation:validate-code
    Scenario: validate-bad-v1code4
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-all" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/overload",
                "version": "1.0.0",
                "code": "code4"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/validate-bad-v1code4-response.json"

    # Validates that code3 with version explicitly pinned to 2.0.0 fails, since code3 only exists in
    # v1.
    @operation:validate-code
    Scenario: validate-bad-v2code3
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-all" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/overload",
                "version": "2.0.0",
                "code": "code3"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/validate-bad-v2code3-response.json"

    # Tests the ambiguous case of code2 with display "Display 2" and no version pin, where the display
    # matches v1 but not v2
    @operation:validate-code
    Scenario: validate-good-code2-v1display
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-all" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/overload",
                "code": "code2",
                "display": "Display 2"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/validate-good-code2-v1display-response.json"

    # Validates code3 against the enum-good value set, which explicitly enumerates it from v1
    @operation:validate-code
    Scenario: validate-good-enum-code3
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-enum-good" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/overload",
                "code": "code3"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/validate-good-enum-code3-response.json"

    # Validates that code4 is accepted by the exclude value set, where it's the only code surviving
    # the v1 exclusion.
    @operation:validate-code
    Scenario: validate-good-exclude-code4
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-exclude" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/overload",
                "code": "code4"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/validate-good-exclude-code4-response.json"

    # Validates that code1 with version pinned to 1.0.0 succeeds, confirming version-pinning works for
    # a code present in both versions.
    @operation:validate-code
    Scenario: validate-good-v1code1
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-all" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/overload",
                "version": "1.0.0",
                "code": "code1"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/validate-good-v1code1-response.json"

    # Validates that code2 with version=1.0.0 and display "Display 2" succeeds, since that's the
    # correct display for v1.
    @operation:validate-code
    Scenario: validate-good-v1code2-display
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-all" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/overload",
                "version": "1.0.0",
                "code": "code2",
                "display": "Display 2"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/validate-good-v1code2-display-response.json"

    # Validates that a codeableConcept with both versions in it works fine.
    @operation:validate-code
    Scenario: validate-good2a
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/overload-all" },
            {
              "name": "codeableConcept",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/test/CodeSystem/overload",
                    "code": "code2",
                    "display": "Display #2"
                  },
                  {
                    "system": "http://hl7.org/fhir/test/CodeSystem/overload",
                    "code": "code2",
                    "display": "Display 2"
                  }
                ]
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "overload/validate-good2a-response.json"
