# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at 5bf53a4adb4a522a34a037fc4f7e797eb2956830).
# Suite "parameters": 35 tests for a FHIR 4.0 server. Do not edit; re-run the generator.
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the expected response is the upstream file,
# fetched at run time and compared as a matchetype by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:parameters @mode:general
Feature: Terminology server — parameters
  Testing out the various expansion parameters that the IG publisher makes use of

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r4"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/5bf53a4adb4a522a34a037fc4f7e797eb2956830/tests/"
    And TxServer is given the resources:
      | resource                                       |
      | simple/codesystem-simple.json                  |
      | simple/valueset-all.json                       |
      | simple/valueset-active.json                    |
      | simple/valueset-inactive.json                  |
      | simple/valueset-enumerated.json                |
      | simple/valueset-filter-isa.json                |
      | simple/valueset-filter-property.json           |
      | simple/valueset-filter-regex.json              |
      | extensions/codesystem-extensions.json          |
      | extensions/codesystem-supplement.json          |
      | extensions/valueset-extensions-enumerated.json |
      | extensions/valueset-extensions-all.json        |
      | extensions/valueset-extensions-all-ns.json     |

  Rule: ValueSet $expand

    # Expand an entire code system, and check that the code system replicates the hierarchy. Note that
    # for all the hierarchical expansions, the flag 'flat' means that the server is not expected to
    # provide a hierarchical expansion
    @operation:expand
    Scenario: parameters-expand-all-hierarchy
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-all" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-all-hierarchy-response-valueSet.json"
      # A server that returns flat expansions is compared with "parameters/parameters-expand-all-hierarchy-response-flat-valueSet.json" instead (generate with --flat).

    # Expand an enumerated value set - no hierarchy in this case
    @operation:expand
    Scenario: parameters-expand-enum-hierarchy
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-enumerated" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-enum-hierarchy-response-valueSet.json"

    # Expand an is-a value set, and preserve the hierarchy
    @operation:expand
    Scenario: parameters-expand-isa-hierarchy
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-isa" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-isa-hierarchy-response-valueSet.json"
      # A server that returns flat expansions is compared with "parameters/parameters-expand-isa-hierarchy-response-flat-valueSet.json" instead (generate with --flat).

    # expand all the active codes - hierarchy is preserved
    @operation:expand
    Scenario: parameters-expand-all-active
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-all" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "activeOnly", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-all-active-response-valueSet.json"
      # A server that returns flat expansions is compared with "parameters/parameters-expand-all-active-response-flat-valueSet.json" instead (generate with --flat).

    # Expand all the active codes, and specify active codes in a parameter
    @operation:expand
    Scenario: parameters-expand-active-active
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-active" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "activeOnly", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-active-active-response-valueSet.json"
      # A server that returns flat expansions is compared with "parameters/parameters-expand-active-active-response-flat-valueSet.json" instead (generate with --flat).

    # Expand all the codes, including inactive ones, but specify active codes only in a parameter
    @operation:expand
    Scenario: parameters-expand-inactive-active
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-active" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "activeOnly", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-inactive-active-response-valueSet.json"
      # A server that returns flat expansions is compared with "parameters/parameters-expand-inactive-active-response-flat-valueSet.json" instead (generate with --flat).

    # Expand an enumerated value set, with active codes only in a parameter
    @operation:expand
    Scenario: parameters-expand-enum-active
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-enumerated" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "activeOnly", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-enum-active-response-valueSet.json"

    # Expand an is-a value set, only the active codes
    @operation:expand
    Scenario: parameters-expand-isa-active
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-isa" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "activeOnly", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-isa-active-response-valueSet.json"
      # A server that returns flat expansions is compared with "parameters/parameters-expand-isa-active-response-flat-valueSet.json" instead (generate with --flat).

    # expand all the active codes, including inactive codes - hierarchy is preserved
    @operation:expand
    Scenario: parameters-expand-all-inactive
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-all" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "activeOnly", "valueBoolean": false },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-all-inactive-response-valueSet.json"
      # A server that returns flat expansions is compared with "parameters/parameters-expand-all-inactive-response-flat-valueSet.json" instead (generate with --flat).

    @operation:expand
    Scenario: parameters-expand-active-inactive
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-active" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "activeOnly", "valueBoolean": false },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-active-inactive-response-valueSet.json"
      # A server that returns flat expansions is compared with "parameters/parameters-expand-active-inactive-response-flat-valueSet.json" instead (generate with --flat).

    @operation:expand
    Scenario: parameters-expand-inactive-inactive
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-inactive" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "activeOnly", "valueBoolean": false },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-inactive-inactive-response-valueSet.json"
      # A server that returns flat expansions is compared with "parameters/parameters-expand-inactive-inactive-response-flat-valueSet.json" instead (generate with --flat).

    @operation:expand
    Scenario: parameters-expand-enum-inactive
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-enumerated" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "activeOnly", "valueBoolean": false },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-enum-inactive-response-valueSet.json"

    @operation:expand
    Scenario: parameters-expand-isa-inactive
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-isa" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "activeOnly", "valueBoolean": false },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-isa-inactive-response-valueSet.json"
      # A server that returns flat expansions is compared with "parameters/parameters-expand-isa-inactive-response-flat-valueSet.json" instead (generate with --flat).

    @operation:expand
    Scenario: parameters-expand-all-designations
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-all" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "includeDesignations", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-all-designations-response-valueSet.json"
      # A server that returns flat expansions is compared with "parameters/parameters-expand-all-designations-response-flat-valueSet.json" instead (generate with --flat).

    @operation:expand
    Scenario: parameters-expand-enum-designations
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-enumerated" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "includeDesignations", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-enum-designations-response-valueSet.json"

    @operation:expand
    Scenario: parameters-expand-isa-designations
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-isa" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "includeDesignations", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-isa-designations-response-valueSet.json"
      # A server that returns flat expansions is compared with "parameters/parameters-expand-isa-designations-response-flat-valueSet.json" instead (generate with --flat).

    @operation:expand
    Scenario: parameters-expand-all-definitions
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-all" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "includeDesignations", "valueBoolean": true },
            { "name": "includeDefinition", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-all-definitions-response-valueSet.json"
      # A server that returns flat expansions is compared with "parameters/parameters-expand-all-definitions-response-flat-valueSet.json" instead (generate with --flat).

    @operation:expand
    Scenario: parameters-expand-enum-definitions
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-enumerated" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "includeDesignations", "valueBoolean": true },
            { "name": "includeDefinition", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-enum-definitions-response-valueSet.json"

    @operation:expand
    Scenario: parameters-expand-isa-definitions
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-isa" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "includeDesignations", "valueBoolean": true },
            { "name": "includeDefinition", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-isa-definitions-response-valueSet.json"
      # A server that returns flat expansions is compared with "parameters/parameters-expand-isa-definitions-response-flat-valueSet.json" instead (generate with --flat).

    @operation:expand
    Scenario: parameters-expand-all-definitions2
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-all" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "includeDesignations", "valueBoolean": true },
            { "name": "includeDefinition", "valueBoolean": true },
            { "name": "property", "valueString": "definition" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-all-definitions2-response-valueSet.json"
      # A server that returns flat expansions is compared with "parameters/parameters-expand-all-definitions2-response-flat-valueSet.json" instead (generate with --flat).

    @operation:expand
    Scenario: parameters-expand-enum-definitions2
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-enumerated" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "includeDesignations", "valueBoolean": true },
            { "name": "includeDefinition", "valueBoolean": true },
            { "name": "property", "valueString": "definition" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-enum-definitions2-response-valueSet.json"

    # specifically to test out http://hl7.org/fhir/StructureDefinition/valueset-concept-definition
    @operation:expand
    Scenario: parameters-expand-enum-definitions3
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/extensions-enumerated" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "includeDesignations", "valueBoolean": true },
            { "name": "includeDefinition", "valueBoolean": true },
            { "name": "property", "valueString": "definition" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-enum-definitions3-response-valueSet.json"

    @operation:expand
    Scenario: parameters-expand-isa-definitions2
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-isa" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "includeDesignations", "valueBoolean": true },
            { "name": "includeDefinition", "valueBoolean": true },
            { "name": "property", "valueString": "definition" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-isa-definitions2-response-valueSet.json"
      # A server that returns flat expansions is compared with "parameters/parameters-expand-isa-definitions2-response-flat-valueSet.json" instead (generate with --flat).

    @operation:expand
    Scenario: parameters-expand-all-property
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-all" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "property", "valueString": "prop" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-all-property-response-valueSet.json"
      # A server that returns flat expansions is compared with "parameters/parameters-expand-all-property-response-flat-valueSet.json" instead (generate with --flat).

    @operation:expand
    Scenario: parameters-expand-enum-property
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-enumerated" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "property", "valueString": "prop" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-enum-property-response-valueSet.json"

    @operation:expand
    Scenario: parameters-expand-isa-property
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-isa" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "property", "valueString": "prop" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-isa-property-response-valueSet.json"
      # A server that returns flat expansions is compared with "parameters/parameters-expand-isa-property-response-flat-valueSet.json" instead (generate with --flat).

    # Base line for supplement tests
    @operation:expand
    Scenario: parameters-expand-supplement-none
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/extensions-all-ns" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-supplement-none-response.json"

    # Make sure the useSupplement parameter works
    @operation:expand
    Scenario: parameters-expand-supplement-good
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/extensions-all-ns" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "useSupplement", "valueCanonical": "http://hl7.org/fhir/test/CodeSystem/supplement" },
            { "name": "property", "valueString": "prop1" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-expand-supplement-good-response.json"

    # Make sure the useSupplement parameter fails when it's not valid
    @operation:expand @http-code:4xx
    Scenario: parameters-expand-supplement-bad
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/extensions-all-ns" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "useSupplement", "valueCanonical": "http://hl7.org/fhir/test/CodeSystem/supplement-X" },
            { "name": "property", "valueString": "prop1" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the expected response "parameters/parameters-expand-supplement-bad-response.json"

  Rule: ValueSet $validate-code

    # Base line for supplement tests - validation
    @operation:validate-code
    Scenario: parameters-validate-supplement-none
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/extensions-all-ns" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/extensions",
                "code": "code1",
                "display": "ectenoot"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-validate-supplement-none-response.json"

    # Make sure the useSupplement parameter works for validation
    @operation:validate-code
    Scenario: parameters-validate-supplement-good
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/extensions-all-ns" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/extensions",
                "code": "code1",
                "display": "ectenoot"
              }
            },
            { "name": "useSupplement", "valueCanonical": "http://hl7.org/fhir/test/CodeSystem/supplement" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-validate-supplement-good-response.json"

    # Make sure the useSupplement parameter fails when it's not valid - for validation
    @operation:validate-code @http-code:4xx
    Scenario: parameters-validate-supplement-bad
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/extensions-all-ns" },
            {
              "name": "coding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/extensions",
                "code": "code1",
                "display": "ectenoot"
              }
            },
            { "name": "useSupplement", "valueCanonical": "http://hl7.org/fhir/test/CodeSystem/supplement-X" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the expected response "parameters/parameters-validate-supplement-bad-response.json"

  Rule: CodeSystem $lookup

    # Base line for supplement tests - validation
    @operation:lookup
    Scenario: parameters-lookup-supplement-none
      When Client looks up a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/extensions" },
            { "name": "code", "valueCode": "code1" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-lookup-supplement-none-response.json"

    # Make sure the useSupplement parameter works for lookup
    @operation:lookup
    Scenario: parameters-lookup-supplement-good
      When Client looks up a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/extensions" },
            { "name": "code", "valueCode": "code1" },
            { "name": "useSupplement", "valueCanonical": "http://hl7.org/fhir/test/CodeSystem/supplement" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "parameters/parameters-lookup-supplement-good-response.json"

    # Make sure the useSupplement parameter fails when it's not valid - for lookup
    @operation:lookup @http-code:4xx
    Scenario: parameters-lookup-supplement-bad
      When Client looks up a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/extensions" },
            { "name": "code", "valueCode": "code1" },
            { "name": "useSupplement", "valueCanonical": "http://hl7.org/fhir/test/CodeSystem/supplement-X" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the expected response "parameters/parameters-lookup-supplement-bad-response.json"
