# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at main).
# Suite "properties": 2 tests for a FHIR 4.0 server. Do not edit; re-run the generator.
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the pattern is the upstream expected-response
# file, which is a matchetype — fetched at run time and compared by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:properties @mode:general
Feature: Terminology server — properties
  Testing the ValueSet.compose.property element

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r4"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/main/tests/"
    And TxServer is given the resources:
      | resource                                                         |
      | properties/codesystem-properties.json                            |
      | properties/valueset-properties-VSCP-all-properties-wildcard.json |
      | properties/valueset-properties-VSCP-all-properties-enums.json    |

  Rule: ValueSet $expand

    # Expand a value set defined to request all properties using ValueSet.compose.property with a
    # wildcard character
    @operation:expand
    Scenario: expand-with-valueset.compose.property-all-properties-wildcard
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/VSCP-all-properties-wildcard" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "properties/expand-with-VSCP-all-properties-wildcard-response.json"

    # Expand a value set defined to request all properties using ValueSet.compose.property with
    # enumerated properties
    @operation:expand
    Scenario: expand-with-valueset.compose.property-all-properties-enums
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/VSCP-all-properties-enums" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "properties/expand-with-VSCP-all-properties-enums-response.json"
