# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at main).
# Suite "regex-bad": 4 tests for a FHIR 4.0 server. Do not edit; re-run the generator.
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the pattern is the upstream expected-response
# file, which is a matchetype — fetched at run time and compared by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:regex-bad @mode:general
Feature: Terminology server — regex-bad
  Bad Regex - checking defences against denial of service attack. These are unusual because
  servers have the option to succeed, or to refuse the request

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r4"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/main/tests/"
    And TxServer is given the resources:
      | resource                              |
      | regex-bad/codesystem-bad-regex.json   |
      | regex-bad/valueset-regex-bad.json     |
      | regex-bad/codesystem-bad-regex-2.json |
      | regex-bad/valueset-regex-bad-2.json   |

  Rule: ValueSet $expand

    # Check expand is safe from catastrophic regex
    @operation:expand
    Scenario: expand-regex-bad
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-regex-bad" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "regex-bad/expand-regex-bad-response.json"

    # Check expand is safe from catastrophic regex
    @operation:expand
    Scenario: expand-regex-bad-2
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-regex-bad-2" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match one of the patterns in:
        | pattern                                    |
        | regex-bad/expand-regex-bad-2-response.json |
        | regex-bad/expand-regex-bad-2-error.json    |

  Rule: ValueSet $validate-code

    # Check validate is safe from catastrophic regex
    @operation:validate-code
    Scenario: validate-regex-bad
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-regex-bad" },
            { "name": "code", "valueCode": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaX" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/bad-regex" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "regex-bad/validate-regex-bad-response.json"

    # Check validate is safe from catastrophic regex
    @operation:validate-code
    Scenario: validate-regex-bad-2
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-regex-bad-2" },
            { "name": "code", "valueCode": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa!" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/regex-bad-2" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match one of the patterns in:
        | pattern                                      |
        | regex-bad/validate-regex-bad-2-response.json |
        | regex-bad/validate-regex-bad-2-error.json    |
