# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at main).
# Suite "simple-cases": 37 tests for a FHIR 5.0 server. Do not edit; re-run the generator.
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the pattern is the upstream expected-response
# file, which is a matchetype — fetched at run time and compared by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:simple-cases @mode:general
Feature: Terminology server — simple-cases
  basic tests, setting up for the API tests to come

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r5"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/main/tests/"
    And TxServer is given the resources:
      | resource                                       |
      | simple/codesystem-simple.json                  |
      | simple/valueset-all.json                       |
      | simple/valueset-active.json                    |
      | simple/valueset-inactive.json                  |
      | simple/valueset-enumerated.json                |
      | simple/valueset-enumerated-bad.json            |
      | simple/valueset-filter-isa.json                |
      | simple/valueset-filter-child-of.json           |
      | simple/valueset-filter-property.json           |
      | simple/valueset-filter-regex.json              |
      | simple/valueset-filter-regex2.json             |
      | simple/valueset-filter-regex-prop.json         |
      | simple/valueset-filter-regex-none.json         |
      | simple/valueset-filter-repeating-property.json |

  Rule: ValueSet $expand

    # Expansion containing all the code system
    @operation:expand
    Scenario: simple-expand-all
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-all" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-expand-all-response-valueSet.json"

    # Expansion containing only the active codes in the code system
    @operation:expand
    Scenario: simple-expand-active
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-active" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-expand-active-response-valueSet.json"

    # Expansion containing only the inactive codes in the code system
    @operation:expand
    Scenario: simple-expand-inactive
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-inactive" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-expand-inactive-response-valueSet.json"

    # Expansion containing an enumerated set of codes in the code system
    @operation:expand
    Scenario: simple-expand-enum
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-enumerated" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-expand-enum-response-valueSet.json"

    # Expansion containing an enumerated set of codes in the code system, including invalid codes
    @operation:expand
    Scenario: simple-expand-enum-bad
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-enumerated-bad" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-expand-enum-bad-response-valueSet.json"

    # Expansion containing a filter on the code system using is-a relationship
    @operation:expand
    Scenario: simple-expand-isa
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-isa" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-expand-isa-response-valueSet.json"

    # Expansion containing a filter on the code system using child-of relationship. This is testing
    # R5/R4 transformation
    @operation:expand
    Scenario: simple-expand-child-of
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-child-of" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-expand-child-of-response-valueSet.json"

    # Expansion containing a filter on the code system using is-a relationship with paging
    # (tx.fhir.org internal test)
    @operation:expand @mode:tx.fhir.org
    Scenario: simple-expand-isa-o2
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-isa" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "offset", "valueInteger": 2 },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-expand-isa-o2-response-valueSet.json"

    # Expansion containing a filter on the code system using is-a relationship with paging
    # (tx.fhir.org internal test)
    @operation:expand @mode:tx.fhir.org
    Scenario: simple-expand-isa-c2
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-isa" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "count", "valueInteger": 2 },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-expand-isa-c2-response-valueSet.json"

    # Expansion containing a filter on the code system using is-a relationship with paging
    # (tx.fhir.org internal test)
    @operation:expand @mode:tx.fhir.org
    Scenario: simple-expand-isa-o2c2
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-isa" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "offset", "valueInteger": 2 },
            { "name": "count", "valueInteger": 2 },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-expand-isa-o2c2-response-valueSet.json"

    # Expansion containing a filter on the code system using a property value
    @operation:expand
    Scenario: simple-expand-prop
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-property" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-expand-prop-response-valueSet.json"

    # A concept may carry several values for one property (CodeSystem.concept.property is 0..*). code3
    # has dup=alpha and dup=beta; filtering on beta - which is not its first value - must still select
    # it
    @operation:expand
    Scenario: simple-expand-repeating-prop
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-repeating-property" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-expand-repeating-prop-response-valueSet.json"

    # expansion.contains.property is 0..* as well: a concept carrying several values for one property
    # must report all of them, not just one
    @operation:expand
    Scenario: simple-expand-repeating-prop-values
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-repeating-property" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "property", "valueCode": "dup" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-expand-repeating-prop-values-response-valueSet.json"

    # Expansion containing a filter on the code system using regex on the codes
    @operation:expand
    Scenario: simple-expand-regex
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-regex" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-expand-regex-response-valueSet.json"

    # Expansion containing a filter on the code system using regex on the codes using a regex known to
    # cause a problem on at least one server
    @operation:expand
    Scenario: simple-expand-regex2
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-regex2" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-expand-regex2-response-valueSet.json"

    # Expansion containing a filter on the code system using regex on the property values of prop
    @operation:expand
    Scenario: simple-expand-regexp-prop
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-regex-prop" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-expand-regex-prop-response-valueSet.json"

    # Expansion containing a filter on the code system using a valid regex on the codes that matches
    # none of them. The expansion is empty - an include whose filter selects nothing must not be
    # treated as an include with no filter, which would select every code in the code system
    @operation:expand
    Scenario: simple-expand-regex-none
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-filter-regex-none" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-expand-regex-none-response-valueSet.json"

    # Expansion containing all the code system, but only a count
    @operation:expand
    Scenario: simple-expand-all-count
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/simple-all" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "count", "valueInteger": 0 },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-expand-all-count-response-valueSet.json"

    # Expansion where the compose refers to a contained value set
    @operation:expand
    Scenario: simple-expand-contained
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "count", "valueInteger": 2000 },
            {
              "name": "valueSet",
              "resource": {
                "resourceType": "ValueSet",
                "id": "relevant-findings",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "valueSet": [
                        "#vs1",
                        "http://hl7.org/fhir/test/ValueSet/simple-filter-isa"
                      ]
                    }
                  ]
                },
                "contained": [
                  {
                    "resourceType": "ValueSet",
                    "id": "vs1",
                    "url": "http://example.org/fhir/ValueSet/relevant-codes",
                    "status": "active",
                    "compose": {
                      "include": [
                        {
                          "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                          "concept": [
                            {
                              "code": "code2"
                            }
                          ]
                        }
                      ]
                    }
                  }
                ]
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-expand-contained-response-valueSet.json"

  Rule: CodeSystem $lookup

    # Check that $lookup works (there's not many tests for $lookup because it's not used much by the
    # tools)
    @operation:lookup
    Scenario: simple-lookup-1
      When Client looks up a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/simple" },
            { "name": "code", "valueCode": "code2a" },
            { "name": "property", "valueCode": "*" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-lookup-response-parameters.json"

    # Check that $lookup works (there's not many tests for $lookup because it's not used much by the
    # tools)
    @operation:lookup
    Scenario: simple-lookup-2
      When Client looks up a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/simple" },
            { "name": "code", "valueCode": "code2" },
            { "name": "property", "valueCode": "*" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-lookup2-response-parameters.json"

  Rule: CodeSystem $subsumes

    # A code subsumes a code nested inside it
    @operation:subsumes
    Scenario: simple-subsumes-parent
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/simple" },
            { "name": "codeA", "valueCode": "code2" },
            { "name": "codeB", "valueCode": "code2a" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-subsumes-parent-response-parameters.json"

    # the mirror of simple-subsumes-parent
    @operation:subsumes
    Scenario: simple-subsumes-child
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/simple" },
            { "name": "codeA", "valueCode": "code2a" },
            { "name": "codeB", "valueCode": "code2" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-subsumes-child-response-parameters.json"

    # A code is equivalent to itself
    @operation:subsumes
    Scenario: simple-subsumes-equivalent
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/simple" },
            { "name": "codeA", "valueCode": "code2a" },
            { "name": "codeB", "valueCode": "code2a" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-subsumes-equivalent-response-parameters.json"

    # Subsumption follows the whole nesting, not just direct children
    @operation:subsumes
    Scenario: simple-subsumes-transitive
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/simple" },
            { "name": "codeA", "valueCode": "code2" },
            { "name": "codeB", "valueCode": "code2aI" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-subsumes-transitive-response-parameters.json"

    # Two sibling codes do not subsume each other
    @operation:subsumes
    Scenario: simple-subsumes-siblings
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/simple" },
            { "name": "codeA", "valueCode": "code2aI" },
            { "name": "codeB", "valueCode": "code2aII" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-subsumes-siblings-response-parameters.json"

    # Two root level codes do not subsume each other
    @operation:subsumes
    Scenario: simple-subsumes-unrelated
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/simple" },
            { "name": "codeA", "valueCode": "code1" },
            { "name": "codeB", "valueCode": "code3" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-subsumes-unrelated-response-parameters.json"

    # A root code does not subsume a code under a different root
    @operation:subsumes
    Scenario: simple-subsumes-root
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/simple" },
            { "name": "codeA", "valueCode": "code1" },
            { "name": "codeB", "valueCode": "code2a" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-subsumes-root-response-parameters.json"

    # codeA is not in the code system
    @operation:subsumes @http-code:4xx
    Scenario: simple-subsumes-unknown-code
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/test/CodeSystem/simple" },
            { "name": "codeA", "valueCode": "code9" },
            { "name": "codeB", "valueCode": "code2" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the pattern in "simple/simple-subsumes-unknown-code-response-parameters.json"

    # As simple-subsumes-parent, but with codingA/codingB
    @operation:subsumes
    Scenario: simple-subsumes-parent-coding
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "codingA",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                "code": "code2"
              }
            },
            {
              "name": "codingB",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                "code": "code2a"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-subsumes-parent-coding-response-parameters.json"

    # As simple-subsumes-child, but with codingA/codingB
    @operation:subsumes
    Scenario: simple-subsumes-child-coding
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "codingA",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                "code": "code2a"
              }
            },
            {
              "name": "codingB",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                "code": "code2"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-subsumes-child-coding-response-parameters.json"

    # As simple-subsumes-equivalent, but with codingA/codingB
    @operation:subsumes
    Scenario: simple-subsumes-equivalent-coding
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "codingA",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                "code": "code2a"
              }
            },
            {
              "name": "codingB",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                "code": "code2a"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-subsumes-equivalent-coding-response-parameters.json"

    # As simple-subsumes-transitive, but with codingA/codingB
    @operation:subsumes
    Scenario: simple-subsumes-transitive-coding
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "codingA",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                "code": "code2"
              }
            },
            {
              "name": "codingB",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                "code": "code2aI"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-subsumes-transitive-coding-response-parameters.json"

    # As simple-subsumes-siblings, but with codingA/codingB
    @operation:subsumes
    Scenario: simple-subsumes-siblings-coding
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "codingA",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                "code": "code2aI"
              }
            },
            {
              "name": "codingB",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                "code": "code2aII"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-subsumes-siblings-coding-response-parameters.json"

    # As simple-subsumes-unrelated, but with codingA/codingB
    @operation:subsumes
    Scenario: simple-subsumes-unrelated-coding
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "codingA",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                "code": "code1"
              }
            },
            {
              "name": "codingB",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                "code": "code3"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-subsumes-unrelated-coding-response-parameters.json"

    # As simple-subsumes-root, but with codingA/codingB
    @operation:subsumes
    Scenario: simple-subsumes-root-coding
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "codingA",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                "code": "code1"
              }
            },
            {
              "name": "codingB",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                "code": "code2a"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "simple/simple-subsumes-root-coding-response-parameters.json"

    # As simple-subsumes-unknown-code, but with codingA/codingB
    @operation:subsumes @http-code:4xx
    Scenario: simple-subsumes-unknown-code-coding
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "codingA",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                "code": "code9"
              }
            },
            {
              "name": "codingB",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/simple",
                "code": "code2"
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the pattern in "simple/simple-subsumes-unknown-code-coding-response-parameters.json"
