# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at main).
# Suite "tx.fhir.org": 76 tests for a FHIR 4.0 server. Do not edit; re-run the generator.
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the expected response is the upstream file,
# fetched at run time and compared as a matchetype by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:tx.fhir.org @mode:tx.fhir.org
Feature: Terminology server — tx.fhir.org
  These are tx.fhir.org specific tests. There's no expectation that other servers will pass these
  tests, and they are not executed by default. (other servers can, but they depend on other set up
  not controlled by the tests
  Upstream mode "tx.fhir.org": a server is expected to pass this suite only when it supports it.

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r4"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/main/tests/"
    And TxServer is given the resources:
      | resource                                             |
      | tx.fhir.org/valueset-all.json                        |
      | tx.fhir.org/valueset-enumerated-bad.json             |
      | tx.fhir.org/valueset-enumerated.json                 |
      | tx.fhir.org/valueset-filter-prop-component.json      |
      | tx.fhir.org/valueset-filter-prop-method.json         |
      | tx.fhir.org/valueset-filter-prop-component-str.json  |
      | tx.fhir.org/valueset-filter-prop-order-obs.json      |
      | tx.fhir.org/valueset-concept-is-a.json               |
      | tx.fhir.org/valueset-filter-copyright.json           |
      | tx.fhir.org/valueset-filter-status.json              |
      | tx.fhir.org/valueset-filter-class-regex.json         |
      | tx.fhir.org/valueset-filter-scale-type.json          |
      | tx.fhir.org/valueset-filter-list.json                |
      | tx.fhir.org/valueset-filter-prop-dockind-exists.json |
      | tx.fhir.org/valueset-filter-classtype.json           |
      | tx.fhir.org/valueset-filter-answers-for1.json        |
      | tx.fhir.org/valueset-filter-answers-for2.json        |
      | tx.fhir.org/valueset-filter-answer-list.json         |
      | tx.fhir.org/valueset-filter-parent.json              |
      | tx.fhir.org/codesystem-loinc-supplement.json         |

  Rule: CodeSystem $validate-code

    @operation:cs-validate-code
    Scenario: snomed-validation-1
      When Client validates a code against the code system on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "code", "valueCode": "276885007000" },
            { "name": "url", "valueUri": "http://snomed.info/sct" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/snomed-validation-1-response-parameters.json"

    @operation:cs-validate-code
    Scenario: loinc-validate-code
      When Client validates a code against the code system on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://loinc.org" },
            { "name": "code", "valueCode": "2339-0" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-code-response-parameters.json"

    @operation:cs-validate-code
    Scenario: loinc-validate-code-uz
      When Client validates a code against the code system on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://loinc.org" },
            { "name": "code", "valueCode": "2339-0" },
            { "name": "displayLanguage", "valueCode": "uz" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-code-uz-response-parameters.json"

    @operation:cs-validate-code
    Scenario: loinc-validate-discouraged-code
      When Client validates a code against the code system on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://loinc.org" },
            { "name": "code", "valueCode": "52495-9" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-code-discouraged-response-parameters.json"

    # LOINC supplement test - code in the supplement, but english
    @operation:cs-validate-code
    Scenario: loinc-validate-code-supp1
      When Client validates a code against the code system on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://loinc.org" },
            { "name": "code", "valueCode": "82810-3" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-code-supp1-response-parameters.json"

    # LOINC supplement test - code in the supplement, but german from the supplement
    @operation:cs-validate-code
    Scenario: loinc-validate-code-supp2
      When Client validates a code against the code system on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://loinc.org" },
            { "name": "code", "valueCode": "82810-3" },
            { "name": "displayLanguage", "valueCode": "de" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-code-supp2-response-parameters.json"

    @operation:cs-validate-code
    Scenario: loinc-validate-part
      When Client validates a code against the code system on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://loinc.org" },
            { "name": "code", "valueCode": "LP111373-9" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-part-response-parameters.json"

    @operation:cs-validate-code
    Scenario: loinc-validate-list
      When Client validates a code against the code system on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://loinc.org" },
            { "name": "code", "valueCode": "LL2972-9" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-list-response-parameters.json"

    @operation:cs-validate-code
    Scenario: loinc-validate-answer
      When Client validates a code against the code system on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://loinc.org" },
            { "name": "code", "valueCode": "LA4489-6" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-answer-response-parameters.json"

    @operation:cs-validate-code
    Scenario: loinc-validate-invalid
      When Client validates a code against the code system on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://loinc.org" },
            { "name": "code", "valueCode": "XX111373-9" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-invalid-response-parameters.json"

  Rule: CodeSystem $lookup

    @operation:lookup
    Scenario: loinc-lookup-code
      When Client looks up a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://loinc.org" },
            { "name": "code", "valueCode": "2339-0" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-lookup-code-response-parameters.json"

    @operation:lookup
    Scenario: loinc-lookup-part
      When Client looks up a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://loinc.org" },
            { "name": "code", "valueCode": "LP111373-9" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-lookup-part-response-parameters.json"

    @operation:lookup
    Scenario: loinc-lookup-list
      When Client looks up a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://loinc.org" },
            { "name": "code", "valueCode": "LL2972-9" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-lookup-list-response-parameters.json"

    @operation:lookup
    Scenario: loinc-lookup-answer
      When Client looks up a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://loinc.org" },
            { "name": "code", "valueCode": "LA4489-6" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-lookup-answer-response-parameters.json"

  Rule: ValueSet $expand

    @operation:expand
    Scenario: loinc-expand-enum
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-enumerated" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-expand-enum-response-valueSet.json"

    @operation:expand @http-code:4xx
    Scenario: loinc-expand-all
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-all" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "limit", "valueInteger": 1000 },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the expected response "tx.fhir.org/loinc-expand-all-response-outcome.json"

    # Attempt to expand the whole HGVS code system: it has a grammar and cannot be iterated, so a
    # not-supported OperationOutcome is expected
    @operation:expand @http-code:4xx
    Scenario: hgvs-expand-all
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "valueSet",
              "resource": {
                "resourceType": "ValueSet",
                "url": "http://hl7.org/fhir/test/ValueSet/hgvs-all",
                "version": "5.0.0",
                "status": "active",
                "compose": {
                  "include": [
                    {
                      "system": "http://varnomen.hgvs.org"
                    }
                  ]
                }
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the expected response "tx.fhir.org/hgvs-expand-all-response-outcome.json"

    @operation:expand
    Scenario: loinc-expand-all-limited
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-all" },
            { "name": "_limit", "valueInteger": 10000 },
            { "name": "count", "valueInteger": 1000 },
            { "name": "offset", "valueInteger": 0 },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-expand-all-limited-response-valueSet.json"

    @operation:expand
    Scenario: loinc-expand-enum-bad
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-enumerated-bad" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-expand-enum-bad-response-valueSet.json"

    @operation:expand
    Scenario: loinc-expand-status
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-status" },
            { "name": "limit", "valueInteger": 10000 },
            { "name": "count", "valueInteger": 100 },
            { "name": "offset", "valueInteger": 0 },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-expand-status-response-valueSet.json"

    @operation:expand
    Scenario: loinc-expand-parent
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-parent" },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-expand-parent-response-valueSet.json"

    @operation:expand
    Scenario: loinc-expand-class-regex
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-class-regex" },
            { "name": "_limit", "valueInteger": 10000 },
            { "name": "count", "valueInteger": 100 },
            { "name": "offset", "valueInteger": 0 },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-expand-class-regex-response-valueSet.json"

    @operation:expand
    Scenario: loinc-expand-prop-component
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-prop-component" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-expand-prop-component-response-valueSet.json"

    @operation:expand
    Scenario: loinc-expand-prop-method
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-method-component" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-expand-prop-method-response-valueSet.json"

    @operation:expand
    Scenario: loinc-expand-prop-component-str
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-prop-component-str" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-expand-prop-component-str-response-valueSet.json"

    @operation:expand
    Scenario: loinc-expand-prop-order-obs
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-prop-order-obs" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "count", "valueInteger": 50 },
            { "name": "offset", "valueInteger": 0 },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-expand-prop-order-obs-response-valueSet.json"

    @operation:expand
    Scenario: loinc-expand-concept-is-a
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-concept-is-a" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-expand-concept-is-a-response-valueSet.json"

    @operation:expand
    Scenario: loinc-expand-copyright
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-copyright" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "count", "valueInteger": 50 },
            { "name": "offset", "valueInteger": 0 },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-expand-copyright-response-valueSet.json"

    @operation:expand
    Scenario: loinc-expand-scale-type
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-scale-type" },
            { "name": "_limit", "valueInteger": 10000 },
            { "name": "count", "valueInteger": 100 },
            { "name": "offset", "valueInteger": 0 },
            { "name": "excludeNested", "valueBoolean": false },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-expand-scale-type-response-valueSet.json"

    @operation:expand
    Scenario: loinc-expand-list-request-parameters
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUrl": "http://loinc.org/vs/LL361-7" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-expand-list-response-valueSet.json"

    @operation:expand
    Scenario: loinc-expand-filter-list-request-parameters
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-list" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-expand-filter-list-response-valueSet.json"

    @operation:expand
    Scenario: loinc-expand-filter-dockind-request-parameters
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-dockind-exists" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "_limit", "valueInteger": 10000 },
            { "name": "count", "valueInteger": 50 },
            { "name": "offset", "valueInteger": 0 },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-expand-prop-dockind-response-valueSet.json"

    # Test answers-for filters with LL code
    @operation:expand
    Scenario: loinc-expand-filter-answers-for1
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-answers-for1" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-expand-filter-answers-for1-response-valueSet.json"

    # Test answers-for filters with normal code
    @operation:expand
    Scenario: loinc-expand-filter-answers-for2
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-answers-for2" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-expand-filter-answers-for2-response-valueSet.json"

    # Test answer-list filters with normal code
    @operation:expand
    Scenario: loinc-expand-filter-answer-list
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-answer-list" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-expand-filter-answer-list-response-valueSet.json"

    # Test the inactive filter
    @operation:expand
    Scenario: snomed-expand-active
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "valueSet",
              "resource": {
                "resourceType": "ValueSet",
                "compose": {
                  "include": [
                    {
                      "system": "http://snomed.info/sct",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "15230009"
                        },
                        {
                          "property": "inactive",
                          "op": "=",
                          "value": "false"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/snomed-expand-active-response-valueSet.json"

    # Test the inactive filter
    @operation:expand
    Scenario: snomed-expand-inactive
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "valueSet",
              "resource": {
                "resourceType": "ValueSet",
                "compose": {
                  "include": [
                    {
                      "system": "http://snomed.info/sct",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "15230009"
                        },
                        {
                          "property": "inactive",
                          "op": "=",
                          "value": "true"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/snomed-expand-inactive-response-valueSet.json"

    # Test the inactive filter
    @operation:expand @http-code:4xx
    Scenario: snomed-expand-inactive2
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "valueSet",
              "resource": {
                "resourceType": "ValueSet",
                "compose": {
                  "include": [
                    {
                      "system": "http://snomed.info/sct",
                      "filter": [
                        {
                          "property": "inactive",
                          "op": "=",
                          "value": "true"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "limit", "valueInteger": 1000 },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the expected response "tx.fhir.org/snomed-expand-inactive2-response-valueSet.json"

    # Test ModuleId filter
    @operation:expand
    Scenario: snomed-expand-moduleid-1
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "valueSet",
              "resource": {
                "resourceType": "ValueSet",
                "compose": {
                  "include": [
                    {
                      "system": "http://snomed.info/sct",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "21522001"
                        },
                        {
                          "property": "moduleId",
                          "op": "=",
                          "value": "900000000000207008"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/snomed-expand-moduleid-1-response.json"

    # Test ModuleId filter
    @operation:expand
    Scenario: snomed-expand-moduleid-2
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "valueSet",
              "resource": {
                "resourceType": "ValueSet",
                "compose": {
                  "include": [
                    {
                      "system": "http://snomed.info/sct",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "21522001"
                        },
                        {
                          "property": "moduleId",
                          "op": "=",
                          "value": "900000000000012004"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/snomed-expand-moduleid-2-response.json"

    # Test ModuleId filter
    @operation:expand
    Scenario: snomed-expand-moduleid-3
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "valueSet",
              "resource": {
                "resourceType": "ValueSet",
                "compose": {
                  "include": [
                    {
                      "system": "http://snomed.info/sct",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "900000000000012004"
                        },
                        {
                          "property": "moduleId",
                          "op": "=",
                          "value": "900000000000207008"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/snomed-expand-moduleid-3-response.json"

    # Test ModuleId filter
    @operation:expand
    Scenario: snomed-expand-moduleid-4
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "valueSet",
              "resource": {
                "resourceType": "ValueSet",
                "compose": {
                  "include": [
                    {
                      "system": "http://snomed.info/sct",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "900000000000012004"
                        },
                        {
                          "property": "moduleId",
                          "op": "=",
                          "value": "900000000000012004"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/snomed-expand-moduleid-4-response.json"

    # Test Property filter
    @operation:expand
    Scenario: snomed-expand-property-1
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "valueSet",
              "resource": {
                "resourceType": "ValueSet",
                "compose": {
                  "include": [
                    {
                      "system": "http://snomed.info/sct",
                      "filter": [
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "195967001"
                        },
                        {
                          "property": "363698007",
                          "op": "=",
                          "value": "89187006"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/snomed-expand-property-1-response.json"

    # Test Property filter
    @operation:expand
    Scenario: snomed-expand-property-2
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "valueSet",
              "resource": {
                "resourceType": "ValueSet",
                "compose": {
                  "include": [
                    {
                      "system": "http://snomed.info/sct",
                      "filter": [
                        {
                          "property": "246075003",
                          "op": "=",
                          "value": "68704007"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/snomed-expand-property-2-response.json"

  Rule: ValueSet $validate-code

    @operation:validate-code
    Scenario: loinc-validate-enum-good
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-enumerated" },
            { "name": "coding", "valueCoding": { "system": "http://loinc.org", "code": "LP111373-9" } },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-enum-good-response-parameters.json"

    @operation:validate-code
    Scenario: loinc-validate-enum-bad
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-enumerated" },
            { "name": "coding", "valueCoding": { "system": "http://loinc.org", "code": "LP111373-9X" } },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-enum-bad-response-parameters.json"

    @operation:validate-code
    Scenario: loinc-validate-filter-prop-component-good
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-prop-component" },
            { "name": "coding", "valueCoding": { "system": "http://loinc.org", "code": "100746-7" } },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-filter-prop-component-good-response-parameters.json"

    @operation:validate-code
    Scenario: loinc-validate-filter-prop-component-bad
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-prop-component" },
            { "name": "coding", "valueCoding": { "system": "http://loinc.org", "code": "10352-3" } },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-filter-prop-component-bad-response-parameters.json"

    @operation:validate-code
    Scenario: loinc-validate-filter-status-good
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-status" },
            { "name": "coding", "valueCoding": { "system": "http://loinc.org", "code": "10879-5" } },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-filter-status-good-response-parameters.json"

    @operation:validate-code
    Scenario: loinc-validate-filter-status-bad
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-status" },
            { "name": "coding", "valueCoding": { "system": "http://loinc.org", "code": "100746-7" } },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-filter-status-bad-response-parameters.json"

    @operation:validate-code
    Scenario: loinc-validate-filter-class-regex-good
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-class-regex" },
            { "name": "coding", "valueCoding": { "system": "http://loinc.org", "code": "100019-9" } },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-filter-class-regex-good-response-parameters.json"

    @operation:validate-code
    Scenario: loinc-validate-filter-class-regex-bad
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-class-regex" },
            { "name": "coding", "valueCoding": { "system": "http://loinc.org", "code": "100746-7" } },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-filter-class-regex-bad-response-parameters.json"

    @operation:validate-code
    Scenario: loinc-validate-filter-scale-type-good
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-scale-type" },
            { "name": "coding", "valueCoding": { "system": "http://loinc.org", "code": "83910-0" } },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-filter-scale-type-good-response-parameters.json"

    @operation:validate-code
    Scenario: loinc-validate-filter-scale-type-bad
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-class-regex" },
            { "name": "coding", "valueCoding": { "system": "http://loinc.org", "code": "100746-7" } },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-filter-scale-type-bad-response-parameters.json"

    @operation:validate-code
    Scenario: loinc-validate-list-good
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://loinc.org/vs/LL361-7" },
            { "name": "coding", "valueCoding": { "system": "http://loinc.org", "code": "LA33-6" } },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-list-good-response-parameters.json"

    @operation:validate-code
    Scenario: loinc-validate-list-bad
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://loinc.org/vs/LL361-7" },
            { "name": "coding", "valueCoding": { "system": "http://loinc.org", "code": "100746-7" } },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-list-bad-response-parameters.json"

    @operation:validate-code
    Scenario: loinc-validate-filter-list-type-good
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-list" },
            { "name": "coding", "valueCoding": { "system": "http://loinc.org", "code": "LA33-6" } },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-filter-list-good-response-parameters.json"

    @operation:validate-code
    Scenario: loinc-validate-filter-list-bad
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-list" },
            { "name": "coding", "valueCoding": { "system": "http://loinc.org", "code": "100746-7" } },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-filter-list-bad-response-parameters.json"

    @operation:validate-code
    Scenario: loinc-validate-filter-dockind-type-good
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-dockind-exists" },
            { "name": "coding", "valueCoding": { "system": "http://loinc.org", "code": "100481-1" } },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-filter-prop-dockind-good-response-parameters.json"

    @operation:validate-code
    Scenario: loinc-validate-filter-dockind-bad
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-dockind-exists" },
            { "name": "coding", "valueCoding": { "system": "http://loinc.org", "code": "10352-3" } },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-filter-prop-dockind-bad-response-parameters.json"

    # test classtype filter (numerical)
    @operation:validate-code
    Scenario: loinc-validate-filter-classtype-good
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-classtype" },
            { "name": "coding", "valueCoding": { "system": "http://loinc.org", "code": "100019-9" } },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-filter-classtype-good-response-parameters.json"

    # test classtype filter (numerical)
    @operation:validate-code
    Scenario: loinc-validate-filter-classtype-bad
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/loinc-filter-classtype" },
            { "name": "coding", "valueCoding": { "system": "http://loinc.org", "code": "44214-5" } },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-validate-filter-classtype-bad-response-parameters.json"

    # Test inactive filter
    @operation:validate-code
    Scenario: snomed-validate-active-bad
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "code", "valueCode": "100005" },
            { "name": "system", "valueUri": "http://snomed.info/sct" },
            {
              "name": "valueSet",
              "resource": {
                "resourceType": "ValueSet",
                "compose": {
                  "include": [
                    {
                      "system": "http://snomed.info/sct",
                      "filter": [
                        {
                          "property": "inactive",
                          "op": "=",
                          "value": "false"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/snomed-validate-active-bad-response.json"

    # Test inactive filter
    @operation:validate-code
    Scenario: snomed-validate-active-good
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "code", "valueCode": "102613000" },
            { "name": "system", "valueUri": "http://snomed.info/sct" },
            {
              "name": "valueSet",
              "resource": {
                "resourceType": "ValueSet",
                "compose": {
                  "include": [
                    {
                      "system": "http://snomed.info/sct",
                      "filter": [
                        {
                          "property": "inactive",
                          "op": "=",
                          "value": "false"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/snomed-validate-active-good-response.json"

    # Test inactive filter
    @operation:validate-code
    Scenario: snomed-validate-inactive-bad
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "code", "valueCode": "102613000" },
            { "name": "system", "valueUri": "http://snomed.info/sct" },
            {
              "name": "valueSet",
              "resource": {
                "resourceType": "ValueSet",
                "compose": {
                  "include": [
                    {
                      "system": "http://snomed.info/sct",
                      "filter": [
                        {
                          "property": "inactive",
                          "op": "=",
                          "value": "true"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/snomed-validate-inactive-bad-response.json"

    # Test inactive filter
    @operation:validate-code
    Scenario: snomed-validate-inactive-good
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "code", "valueCode": "100005" },
            { "name": "system", "valueUri": "http://snomed.info/sct" },
            {
              "name": "valueSet",
              "resource": {
                "resourceType": "ValueSet",
                "compose": {
                  "include": [
                    {
                      "system": "http://snomed.info/sct",
                      "filter": [
                        {
                          "property": "inactive",
                          "op": "=",
                          "value": "true"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/snomed-validate-inactive-good-response.json"

    # Test moduleid filter
    @operation:validate-code
    Scenario: snomed-validate-moduleid-bad
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "code", "valueCode": "102613000" },
            { "name": "system", "valueUri": "http://snomed.info/sct" },
            {
              "name": "valueSet",
              "resource": {
                "resourceType": "ValueSet",
                "compose": {
                  "include": [
                    {
                      "system": "http://snomed.info/sct",
                      "filter": [
                        {
                          "property": "moduleId",
                          "op": "=",
                          "value": "900000000000012004"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/snomed-validate-moduleid-bad-response.json"

    # Test moduleid filter
    @operation:validate-code
    Scenario: snomed-validate-moduleid-good
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "code", "valueCode": "102613000" },
            { "name": "system", "valueUri": "http://snomed.info/sct" },
            {
              "name": "valueSet",
              "resource": {
                "resourceType": "ValueSet",
                "compose": {
                  "include": [
                    {
                      "system": "http://snomed.info/sct",
                      "filter": [
                        {
                          "property": "moduleId",
                          "op": "=",
                          "value": "900000000000207008"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/snomed-validate-moduleid-good-response.json"

    # Test Property filter
    @operation:validate-code
    Scenario: snomed-validate-property-bad
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "code", "valueCode": "10674711000119105" },
            { "name": "system", "valueUri": "http://snomed.info/sct" },
            {
              "name": "valueSet",
              "resource": {
                "resourceType": "ValueSet",
                "compose": {
                  "include": [
                    {
                      "system": "http://snomed.info/sct",
                      "filter": [
                        {
                          "property": "363698007",
                          "op": "=",
                          "value": "89187006"
                        },
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "195967001"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/snomed-validate-property-bad-response.json"

    # Test Property filter
    @operation:validate-code
    Scenario: snomed-validate-property-good
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "code", "valueCode": "10674791000119101" },
            { "name": "system", "valueUri": "http://snomed.info/sct" },
            {
              "name": "valueSet",
              "resource": {
                "resourceType": "ValueSet",
                "compose": {
                  "include": [
                    {
                      "system": "http://snomed.info/sct",
                      "filter": [
                        {
                          "property": "363698007",
                          "op": "=",
                          "value": "89187006"
                        },
                        {
                          "property": "concept",
                          "op": "is-a",
                          "value": "195967001"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/snomed-validate-property-good-response.json"

  Rule: ConceptMap $translate

    # Implicit Snomed Concept Map
    @operation:translate
    Scenario: snomed-translate
      When Client translates on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://snomed.info/sct?fhir_cm=900000000000526001" },
            { "name": "code", "valueCode": "225983005" },
            { "name": "sourceSystem", "valueUri": "http://snomed.info/sct" },
            { "name": "targetSystem", "valueUri": "http://snomed.info/sct" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/snomed-translate-response.json"

  Rule: CodeSystem $subsumes

    # A LOINC code is equivalent to itself
    @operation:subsumes
    Scenario: loinc-subsumes-equivalent
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://loinc.org" },
            { "name": "codeA", "valueCode": "2339-0" },
            { "name": "codeB", "valueCode": "2339-0" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-subsumes-equivalent-response-parameters.json"

    # A LOINC part subsumes a code beneath it in the multiaxial hierarchy
    @operation:subsumes
    Scenario: loinc-subsumes-parent
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://loinc.org" },
            { "name": "codeA", "valueCode": "LP385526-1" },
            { "name": "codeB", "valueCode": "2339-0" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-subsumes-parent-response-parameters.json"

    # the mirror of loinc-subsumes-parent
    @operation:subsumes
    Scenario: loinc-subsumes-child
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://loinc.org" },
            { "name": "codeA", "valueCode": "2339-0" },
            { "name": "codeB", "valueCode": "LP385526-1" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-subsumes-child-response-parameters.json"

    # Two unrelated LOINC codes
    @operation:subsumes
    Scenario: loinc-subsumes-unrelated
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://loinc.org" },
            { "name": "codeA", "valueCode": "2339-0" },
            { "name": "codeB", "valueCode": "52495-9" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "tx.fhir.org/loinc-subsumes-unrelated-response-parameters.json"

    # codeA is not a LOINC code
    @operation:subsumes @http-code:4xx
    Scenario: loinc-subsumes-unknown-code
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://loinc.org" },
            { "name": "codeA", "valueCode": "99999-9" },
            { "name": "codeB", "valueCode": "2339-0" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the expected response "tx.fhir.org/loinc-subsumes-unknown-code-response-parameters.json"
