# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at main).
# Suite "translate": 7 tests for a FHIR 5.0 server. Do not edit; re-run the generator.
# Left out, bound to another FHIR version: translate-1-r4-code (4.0), translate-1-r4-coding (4.0), translate-1-r4-codeableconcept (4.0).
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the pattern is the upstream expected-response
# file, which is a matchetype — fetched at run time and compared by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:translate @mode:general
Feature: Terminology server — translate
  Tests for ConceptMap.$translate

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r5"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/main/tests/"
    And TxServer is given the resources:
      | resource                         |
      | translate/codesystem-source.json |
      | translate/codesystem-target.json |
      | translate/ConceptMap-full.json   |
      | translate/ConceptMap-novs.json   |
      | translate/valueset-source.json   |
      | translate/valueset-target.json   |

  Rule: ConceptMap $translate

    # A very simple translation, using sourceCode + sourceSystem
    @operation:translate
    Scenario: translate-1
      When Client translates on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "sourceSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/source" },
            { "name": "sourceCode", "valueCode": "code-1" },
            { "name": "targetSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/target" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "translate/translate-1-response-parameters.json"

    # The same translation, but naming the source concept with sourceCoding
    @operation:translate
    Scenario: translate-1-coding
      When Client translates on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "sourceCoding",
              "valueCoding": {
                "system": "http://hl7.org/fhir/test/CodeSystem/source",
                "code": "code-1"
              }
            },
            { "name": "targetSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/target" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "translate/translate-1-coding-response-parameters.json"

    # The same translation, but naming the source concept with sourceCodeableConcept
    @operation:translate
    Scenario: translate-1-codeableconcept
      When Client translates on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            {
              "name": "sourceCodeableConcept",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/test/CodeSystem/source",
                    "code": "code-1"
                  }
                ]
              }
            },
            { "name": "targetSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/target" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "translate/translate-1-codeableconcept-response-parameters.json"

    # Testing different relationship types
    @operation:translate
    Scenario: translate-2
      When Client translates on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "sourceSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/source" },
            { "name": "sourceCode", "valueCode": "code-2" },
            { "name": "targetSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/target" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "translate/translate-2-response-parameters.json"

    # Testing different relationship types
    @operation:translate
    Scenario: translate-2b
      When Client translates on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "sourceSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/source" },
            { "name": "sourceCode", "valueCode": "code-2b" },
            { "name": "targetSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/target" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "translate/translate-2b-response-parameters.json"

    # Testing different relationship types
    @operation:translate
    Scenario: translate-3
      When Client translates on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "sourceSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/source" },
            { "name": "sourceCode", "valueCode": "code-3" },
            { "name": "targetSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/target" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "translate/translate-3-response-parameters.json"

    # Testing nomap functionality. In R4 the ConceptMap states this with a codeless 'unmatched'
    # target; either way the response reports noMap and no concept
    @operation:translate
    Scenario: translate-4
      When Client translates on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "sourceSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/source" },
            { "name": "sourceCode", "valueCode": "code-4" },
            { "name": "targetSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/target" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "translate/translate-4-response-parameters.json"
