# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at main).
# Suite "tho": 32 tests for a FHIR 4.0 server. Do not edit; re-run the generator.
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the pattern is the upstream expected-response
# file, which is a matchetype — fetched at run time and compared by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:tho @mode:general
Feature: Terminology server — tho
  Misc assorted test cases from tho

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r4"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/main/tests/"
    And TxServer is given the resources:
      | resource                                |
      | tho/cs-act-class.json                   |
      | tho/cs-act-reason.json                  |
      | tho/vs-act-class.json                   |
      | tho/vs-act-class-isa.json               |
      | tho/vs-act-class-descendent-of.json     |
      | tho/vs-act-class-isnota.json            |
      | tho/vs-act-class-isa-second-parent.json |
      | tho/vs-act-class-child-of.json          |

  Rule: ValueSet $expand

    # act class - don't remember what bug this was testing for but now it tests for proper handling of
    # retired and deprecated codes
    @operation:expand
    Scenario: act-class
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUrl": "http://hl7.org/fhir/tests/ValueSet/act-class" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/expand-vs-act-class-response-valueSet.json"

    # tests for proper handling of retired and deprecated codes (part 2)
    @operation:expand
    Scenario: act-class-activeonly
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUrl": "http://hl7.org/fhir/tests/ValueSet/act-class" },
            { "name": "excludeNested", "valueBoolean": true },
            { "name": "activeOnly", "valueBoolean": true },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/expand-vs-act-class-activeonly-response-valueSet.json"

    # tests for proper handling of excluded codes
    @operation:expand
    Scenario: act-exclusion
      # The request holds a character an ITB expression cannot carry, so it is
      # fetched from the test material rather than written out here.
      When Client expands on TxServer with the request in "tho/expand-vs-act-exclusion-request.json" and the parameters in "parameters-default.json"
      Then $response.status should be 200
      And $response should match the pattern in "tho/expand-vs-act-exclusion-response.json"

  Rule: CodeSystem $subsumes

    # a code subsumes a code that names it in a subsumedBy property; act-class is a flat list, so
    # there is no nesting to read
    @operation:subsumes
    Scenario: subsumes-act-class-property-parent
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "codeA", "valueCode": "_ActClassRecordOrganizer" },
            { "name": "codeB", "valueCode": "COMPOSITION" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/subsumes-act-class-property-parent-response.json"

    # the mirror of subsumes-act-class-property-parent
    @operation:subsumes
    Scenario: subsumes-act-class-property-child
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "codeA", "valueCode": "COMPOSITION" },
            { "name": "codeB", "valueCode": "_ActClassRecordOrganizer" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/subsumes-act-class-property-child-response.json"

    # subsumption follows the whole chain of subsumedBy properties, five links here
    @operation:subsumes
    Scenario: subsumes-act-class-transitive
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "codeA", "valueCode": "ACT" },
            { "name": "codeB", "valueCode": "CDALVLONE" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/subsumes-act-class-transitive-response.json"

    # the mirror of subsumes-act-class-transitive
    @operation:subsumes
    Scenario: subsumes-act-class-transitive-reverse
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "codeA", "valueCode": "CDALVLONE" },
            { "name": "codeB", "valueCode": "ACT" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/subsumes-act-class-transitive-reverse-response.json"

    # a code is equivalent to itself
    @operation:subsumes
    Scenario: subsumes-act-class-equivalent
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "codeA", "valueCode": "DOC" },
            { "name": "codeB", "valueCode": "DOC" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/subsumes-act-class-equivalent-response.json"

    # two codes with the same subsumedBy do not subsume each other
    @operation:subsumes
    Scenario: subsumes-act-class-siblings
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "codeA", "valueCode": "COMPOSITION" },
            { "name": "codeB", "valueCode": "FOLDER" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/subsumes-act-class-siblings-response.json"

    # both codes are under ACT, but neither is on the other's path to it
    @operation:subsumes
    Scenario: subsumes-act-class-cross-branch
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "codeA", "valueCode": "_ActClassContainer" },
            { "name": "codeB", "valueCode": "COMPOSITION" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/subsumes-act-class-cross-branch-response.json"

    # ENTRY states subsumedBy twice: this is the first parent
    @operation:subsumes
    Scenario: subsumes-act-class-multiple-parents-first
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "codeA", "valueCode": "_ActClassContainer" },
            { "name": "codeB", "valueCode": "ENTRY" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/subsumes-act-class-multiple-parents-first-response.json"

    # and this is the second - a relationship a nested hierarchy cannot express at all
    @operation:subsumes
    Scenario: subsumes-act-class-multiple-parents-second
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "codeA", "valueCode": "_ActContainer" },
            { "name": "codeB", "valueCode": "ENTRY" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/subsumes-act-class-multiple-parents-second-response.json"

    # two parents of the same code are not thereby related to each other
    @operation:subsumes
    Scenario: subsumes-act-class-multiple-parents-crossed
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "codeA", "valueCode": "_ActClassContainer" },
            { "name": "codeB", "valueCode": "_ActContainer" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/subsumes-act-class-multiple-parents-crossed-response.json"

    # codeB is not in the code system
    @operation:subsumes @http-code:4xx
    Scenario: subsumes-act-class-unknown-code
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "codeA", "valueCode": "ACT" },
            { "name": "codeB", "valueCode": "code9" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the pattern in "tho/subsumes-act-class-unknown-code-response.json"

  Rule: ValueSet $validate-code

    # is-a includes the code named in the filter, not just what is under it
    @operation:validate-code
    Scenario: validate-isa-self
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/tests/ValueSet/act-class-isa" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "code", "valueCode": "_ActClassRecordOrganizer" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/validate-isa-self-response.json"

    # a code that names the filter code in a subsumedBy property is in the value set
    @operation:validate-code
    Scenario: validate-isa-child
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/tests/ValueSet/act-class-isa" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "code", "valueCode": "COMPOSITION" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/validate-isa-child-response.json"

    # and so is one five property links below it
    @operation:validate-code
    Scenario: validate-isa-deep
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/tests/ValueSet/act-class-isa" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "code", "valueCode": "CDALVLONE" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/validate-isa-deep-response.json"

    # is-a runs downwards: the code above the filter code is not in the value set
    @operation:validate-code
    Scenario: validate-isa-parent
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/tests/ValueSet/act-class-isa" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "code", "valueCode": "ACT" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/validate-isa-parent-response.json"

    # a code in a different branch of the same code system is not in it either
    @operation:validate-code
    Scenario: validate-isa-other-branch
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/tests/ValueSet/act-class-isa" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "code", "valueCode": "ENTRY" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/validate-isa-other-branch-response.json"

    # descendent-of excludes the code named in the filter - the one thing that distinguishes it from
    # is-a
    @operation:validate-code
    Scenario: validate-descendent-of-self
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/tests/ValueSet/act-class-descendent-of" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "code", "valueCode": "_ActClassRecordOrganizer" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/validate-descendent-of-self-response.json"

    # everything below the filter code is in it, exactly as for is-a
    @operation:validate-code
    Scenario: validate-descendent-of-child
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/tests/ValueSet/act-class-descendent-of" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "code", "valueCode": "COMPOSITION" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/validate-descendent-of-child-response.json"

    # including the deep descendants
    @operation:validate-code
    Scenario: validate-descendent-of-deep
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/tests/ValueSet/act-class-descendent-of" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "code", "valueCode": "CDALVLONE" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/validate-descendent-of-deep-response.json"

    # is-not-a excludes the code named in the filter as well as its descendants
    @operation:validate-code
    Scenario: validate-isnota-self
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/tests/ValueSet/act-class-isnota" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "code", "valueCode": "_ActClassRecordOrganizer" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/validate-isnota-self-response.json"

    # a deep descendant of the filter code is excluded too, not just the direct children
    @operation:validate-code
    Scenario: validate-isnota-descendant
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/tests/ValueSet/act-class-isnota" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "code", "valueCode": "CDALVLONE" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/validate-isnota-descendant-response.json"

    # the code above the filter code is in an is-not-a value set
    @operation:validate-code
    Scenario: validate-isnota-parent
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/tests/ValueSet/act-class-isnota" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "code", "valueCode": "ACT" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/validate-isnota-parent-response.json"

    # and so is a code in a different branch
    @operation:validate-code
    Scenario: validate-isnota-other-branch
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/tests/ValueSet/act-class-isnota" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "code", "valueCode": "ENTRY" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/validate-isnota-other-branch-response.json"

    # child-of picks up a direct child, which act-class states in a subsumedBy property rather than by
    # nesting
    @operation:validate-code
    Scenario: validate-child-of-child
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/tests/ValueSet/act-class-child-of" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "code", "valueCode": "COMPOSITION" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/validate-child-of-child-response.json"

    # child-of does not include the code named in the filter, unlike is-a
    @operation:validate-code
    Scenario: validate-child-of-self
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/tests/ValueSet/act-class-child-of" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "code", "valueCode": "_ActClassRecordOrganizer" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/validate-child-of-self-response.json"

    # and it stops at the direct children, which is what separates it from descendent-of
    @operation:validate-code
    Scenario: validate-child-of-grandchild
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/tests/ValueSet/act-class-child-of" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "code", "valueCode": "CDALVLONE" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/validate-child-of-grandchild-response.json"

    # ENTRY is in an is-a on _ActContainer, the second of its two subsumedBy parents - a relationship
    # nesting cannot express
    @operation:validate-code
    Scenario: validate-isa-second-parent
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/tests/ValueSet/act-class-isa-second-parent" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "code", "valueCode": "ENTRY" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/validate-isa-second-parent-response.json"

    # a code under the other container is not in it
    @operation:validate-code
    Scenario: validate-isa-second-parent-out
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/tests/ValueSet/act-class-isa-second-parent" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "code", "valueCode": "COMPOSITION" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/validate-isa-second-parent-out-response.json"

    # a code that is not in the code system at all, validated against a filtered value set
    @operation:validate-code
    Scenario: validate-isa-unknown-code
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/tests/ValueSet/act-class-isa" },
            { "name": "system", "valueUri": "http://hl7.org/fhir/tests/CodeSystem/act-class" },
            { "name": "code", "valueCode": "code9" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "tho/validate-isa-unknown-code-response.json"
