# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at main).
# Suite "translate2": 6 tests for a FHIR 5.0 server. Do not edit; re-run the generator.
# Left out, bound to another FHIR version: translate-reverse-r4 (4.0), translate-reverse-r4-a (4.0), translate-reverse-r4-b (4.0).
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the pattern is the upstream expected-response
# file, which is a matchetype — fetched at run time and compared by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:translate2 @mode:general
Feature: Terminology server — translate2
  Tests for ConceptMap.$translate

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r5"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/main/tests/"
    And TxServer is given the resources:
      | resource                            |
      | translate/codesystem-source.json    |
      | translate/codesystem-target.json    |
      | translate/ConceptMap-full.json      |
      | translate/ConceptMap-othermap.json  |
      | translate/ConceptMap-othermap2.json |
      | translate/ConceptMap-novs.json      |
      | translate/valueset-source.json      |
      | translate/valueset-target.json      |

  Rule: ConceptMap $translate

    # Testing unmapped functionality
    @operation:translate
    Scenario: translate-5
      When Client translates on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "sourceSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/source" },
            { "name": "sourceCode", "valueCode": "code-5" },
            { "name": "targetSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/target" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "translate/translate-5-response-parameters.json"

    # Testing unmapped functionality which specifying a particular map
    @operation:translate
    Scenario: translate-5a
      When Client translates on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "sourceSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/source" },
            { "name": "sourceCode", "valueCode": "code-5" },
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ConceptMap/full" },
            { "name": "targetSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/target" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "translate/translate-5a-response-parameters.json"

    # Testing unmapped functionality which specifying a particular map
    @operation:translate
    Scenario: translate-5b
      When Client translates on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "sourceSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/source" },
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ConceptMap/othermap" },
            { "name": "sourceCode", "valueCode": "code-5" },
            { "name": "targetSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/target" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "translate/translate-5b-response-parameters.json"

    # Testing other map - default concept map
    @operation:translate
    Scenario: translate-6a
      When Client translates on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "sourceSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/source" },
            { "name": "sourceCode", "valueCode": "code-5" },
            { "name": "targetSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/target" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "translate/translate-5-response-parameters.json"

    # Same translation, but in reverse
    @operation:translate @fhir-version:!4.0
    Scenario: translate-reverse-r5+
      When Client translates on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "sourceSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/source" },
            { "name": "targetCode", "valueCode": "code1" },
            { "name": "targetSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/target" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the pattern in "translate/translate-reverse-response-r5-parameters.json"

    # reverse is not allowed in R5
    @operation:translate @fhir-version:!4.0 @http-code:4xx
    Scenario: translate-reverse-r5+-a
      When Client translates on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "sourceSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/source" },
            { "name": "sourceCode", "valueCode": "code-1" },
            { "name": "reverse", "valueBoolean": true },
            { "name": "targetSystem", "valueUri": "http://hl7.org/fhir/test/CodeSystem/target" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the pattern in "translate/translate-reverse-response-r5-a-outcome.json"
