# Generated by scripts/tx-tests.mjs from the HL7 FHIR terminology-ecosystem tests
# (https://github.com/HL7/fhir-tx-ecosystem-ig, tests/test-cases.json at 5bf53a4adb4a522a34a037fc4f7e797eb2956830).
# Suite "UCUM": 19 tests for a FHIR 4.0 server. Do not edit; re-run the generator.
# Left out, bound to another FHIR version: expand-ucum-all-5 (5.0).
#
# Each scenario is one upstream test: the request is the upstream Parameters with the
# runner's profile parameters merged in, and the expected response is the upstream file,
# fetched at run time and compared as a matchetype by the FHIR validator.
@lang:itb-core-en@^2 @dialect:fhir-terminology@^1 @dialect:fhir-validator@^2 @suite:UCUM @mode:tx.fhir.org
Feature: Terminology server — UCUM
  UCUM Test Cases
  Upstream mode "tx.fhir.org": a server is expected to pass this suite only when it supports it.

  Background:
    Given TxServer is the system under test at "https://178.104.103.200.sslip.io/tx/r4"
    And FHIRValidator is a fhir-validator at "http://fhir-validator:8080"
    And Client is infrastructure
    And Client fetches the test material from "https://raw.githubusercontent.com/HL7/fhir-tx-ecosystem-ig/5bf53a4adb4a522a34a037fc4f7e797eb2956830/tests/"
    And TxServer is given the resources:
      | resource                          |
      | ucum/valueset-ucum-all.json       |
      | ucum/valueset-ucum-canonical.json |

  Rule: CodeSystem $lookup

    # Tests the $lookup operation
    @operation:lookup
    Scenario: lookup
      When Client looks up a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://unitsofmeasure.org" },
            { "name": "code", "valueCode": "mg/dL" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "ucum/lookup-simple-code-response.json"

    # Tests the $lookup operation with annotation
    @operation:lookup
    Scenario: lookup-with-annotation
      When Client looks up a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://unitsofmeasure.org" },
            { "name": "code", "valueCode": "mg/dL{milligram per deciliter}" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "ucum/lookup-with-annotation-code-response.json"

  Rule: ValueSet $expand

    # Tests the $expand operation for all codes (this is a special case). The special value set
    # changed between R4 and R5
    @operation:expand @fhir-version:4.0
    Scenario: expand-ucum-all-4
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/ucum-all" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "ucum/expand-ucum-all-4-response.json"

    # Tests the $expand operation for all codes (this is a special case)
    @operation:expand
    Scenario: expand-ucum-canonical
      When Client expands on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/ucum-canonical" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "ucum/expand-ucum-canonical-response.json"

  Rule: ValueSet $validate-code

    # Tests the $validate-code operation for a valid UCUM code
    @operation:validate-code
    Scenario: validate-ucum-canonical-good
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/ucum-canonical" },
            { "name": "system", "valueUri": "http://unitsofmeasure.org" },
            { "name": "code", "valueUri": "kg" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "ucum/validate-ucum-canonical-good-response.json"

    # Tests the $validate-code operation for an valid UCUM code not in the canonicl value set
    @operation:validate-code
    Scenario: validate-ucum-canonical-bad
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/ucum-canonical" },
            { "name": "system", "valueUri": "http://unitsofmeasure.org" },
            { "name": "code", "valueUri": "mL" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "ucum/validate-ucum-canonical-bad-response.json"

    # Tests the $validate-code operation for a valid UCUM code
    @operation:validate-code
    Scenario: validate-all-canonical-good
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/ucum-all" },
            { "name": "system", "valueUri": "http://unitsofmeasure.org" },
            { "name": "code", "valueUri": "kg" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "ucum/validate-ucum-all-good-response.json"

    # Tests the $validate-code operation for an invalid UCUM code
    @operation:validate-code
    Scenario: validate-ucum-all-bad
      When Client validates a code on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "url", "valueUri": "http://hl7.org/fhir/test/ValueSet/ucum-all" },
            { "name": "system", "valueUri": "http://unitsofmeasure.org" },
            { "name": "code", "valueUri": "kgXX" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "ucum/validate-ucum-all-bad-response.json"

  Rule: CodeSystem $subsumes

    # A unit is equivalent to itself
    @operation:subsumes
    Scenario: ucum-subsumes-equivalent
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://unitsofmeasure.org" },
            { "name": "codeA", "valueCode": "mg/dL" },
            { "name": "codeB", "valueCode": "mg/dL" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "ucum/ucum-subsumes-equivalent-response.json"

    # The same unit written two different ways
    @operation:subsumes
    Scenario: ucum-subsumes-canonical
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://unitsofmeasure.org" },
            { "name": "codeA", "valueCode": "1/min" },
            { "name": "codeB", "valueCode": "min-1" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "ucum/ucum-subsumes-canonical-response.json"

    # Two unrelated units
    @operation:subsumes
    Scenario: ucum-subsumes-unrelated
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://unitsofmeasure.org" },
            { "name": "codeA", "valueCode": "mg/dL" },
            { "name": "codeB", "valueCode": "mm[Hg]" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "ucum/ucum-subsumes-unrelated-response.json"

    # A unit and a scaled version of it - UCUM has no hierarchy
    @operation:subsumes
    Scenario: ucum-subsumes-scaled
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://unitsofmeasure.org" },
            { "name": "codeA", "valueCode": "m" },
            { "name": "codeB", "valueCode": "cm" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "ucum/ucum-subsumes-scaled-response.json"

    # codeA is not a valid UCUM unit
    @operation:subsumes @http-code:4xx
    Scenario: ucum-subsumes-invalid-code
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://unitsofmeasure.org" },
            { "name": "codeA", "valueCode": "not-a-unit" },
            { "name": "codeB", "valueCode": "mg/dL" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should match "^4"
      And $response should match the expected response "ucum/ucum-subsumes-invalid-code-response.json"

    # A unit with an annotation, and the same unit without
    @operation:subsumes
    Scenario: ucum-subsumes-annotation
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://unitsofmeasure.org" },
            { "name": "codeA", "valueCode": "mg{total}" },
            { "name": "codeB", "valueCode": "mg" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "ucum/ucum-subsumes-annotation-response.json"

    # A named derived unit and the expression it is defined as
    @operation:subsumes
    Scenario: ucum-subsumes-derived
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://unitsofmeasure.org" },
            { "name": "codeA", "valueCode": "N" },
            { "name": "codeB", "valueCode": "kg.m/s2" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "ucum/ucum-subsumes-derived-response.json"

    # Two units of the same property whose conversion has an offset
    @operation:subsumes
    Scenario: ucum-subsumes-offset
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://unitsofmeasure.org" },
            { "name": "codeA", "valueCode": "Cel" },
            { "name": "codeB", "valueCode": "K" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "ucum/ucum-subsumes-offset-response.json"

    # Two units with the same canonical unit but different magnitudes
    @operation:subsumes
    Scenario: ucum-subsumes-same-canonical
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://unitsofmeasure.org" },
            { "name": "codeA", "valueCode": "mg/dL" },
            { "name": "codeB", "valueCode": "g/L" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "ucum/ucum-subsumes-same-canonical-response.json"

    # The same canonical unit again, with neither magnitude being 1
    @operation:subsumes
    Scenario: ucum-subsumes-both-scaled
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://unitsofmeasure.org" },
            { "name": "codeA", "valueCode": "[in_i]" },
            { "name": "codeB", "valueCode": "cm" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "ucum/ucum-subsumes-both-scaled-response.json"

    # Two dimensionless units, told apart only by magnitude
    @operation:subsumes
    Scenario: ucum-subsumes-dimensionless
      When Client tests subsumption on TxServer with:
        """
        {
          "resourceType": "Parameters",
          "parameter": [
            { "name": "system", "valueUri": "http://unitsofmeasure.org" },
            { "name": "codeA", "valueCode": "%" },
            { "name": "codeB", "valueCode": "1" },
            { "name": "uuid", "valueUuid": "urn:uuid:8acdbfdc-e9d2-11ed-a05b-0242ac120003" }
          ]
        }
        """
      Then $response.status should be 200
      And $response should match the expected response "ucum/ucum-subsumes-dimensionless-response.json"
